-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["素布腰带"] = {
	type = "Belt",
	tags = { default = true, belt = true, },
	implicit = "物理伤害提高 (12-24)%",
	req = { },
}
itemBases["扣链腰带"] = {
	type = "Belt",
	tags = { default = true, belt = true, },
	implicit = "+(9-20) 最大能量护盾",
	req = { },
}
itemBases["皮革腰带"] = {
	type = "Belt",
	tags = { default = true, belt = true, },
	implicit = "+(25-40) 最大生命",
	req = { level = 8, },
}
itemBases["重革腰带"] = {
	type = "Belt",
	tags = { default = true, belt = true, },
	implicit = "+(25-35) 力量",
	req = { level = 8, },
}
itemBases["饰布腰带"] = {
	type = "Belt",
	tags = { default = true, belt = true, },
	implicit = "晕眩回复和格挡回复提高 (15-25)%",
	req = { level = 16, },
}
itemBases["扣钉腰带"] = {
	type = "Belt",
	tags = { default = true, belt = true, },
	implicit = "敌人被晕眩时间延长 (20-30)%",
	req = { level = 16, },
}
itemBases["先锋腰带"] = {
	type = "Belt",
	tags = { default = true, belt = true, not_for_sale = true, atlas_base_type = true, beltatlas1 = true, },
	implicit = "+(260-320) 护甲和闪避值",
	req = { level = 78, },
}
itemBases["水晶腰带"] = {
	type = "Belt",
	tags = { default = true, belt = true, not_for_sale = true, atlas_base_type = true, beltatlas2 = true, },
	implicit = "+(60-80) 最大能量护盾",
	req = { level = 79, },
}
itemBases["深渊腰带"] = {
	type = "Belt",
	tags = { default = true, belt = true, not_for_sale = true, },
	implicit = "拥有 1 个深渊插槽",
	req = { },
}

itemBases["金羽腰带"] = {
	type = "Belt",
	hidden = true,
	tags = { default = true, belt = true, not_for_sale = true, },
	implicit = "物品稀有度提高 (20-30)%",
	req = { },
}
