-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["朽木之棒"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 6, PhysicalMax = 8, CritChanceBase = 5, AttackRateBase = 1.45,  Range = 9,},
	req = { str = 14, },
}
itemBases["祭仪之杵"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 9, PhysicalMax = 14, CritChanceBase = 5, AttackRateBase = 1.35,  Range = 9,},
	req = { level = 5, str = 26, },
}
itemBases["钝钉木棒"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 13, PhysicalMax = 17, CritChanceBase = 5, AttackRateBase = 1.4, Range = 9, },
	req = { level = 10, str = 41, },
}
itemBases["石锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 15%",
	weapon = { PhysicalMin = 17, PhysicalMax = 32, CritChanceBase = 5, AttackRateBase = 1.15,  Range = 9,},
	req = { level = 15, str = 56, },
}
itemBases["战锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 14, PhysicalMax = 32, CritChanceBase = 5, AttackRateBase = 1.4,  Range = 9,},
	req = { level = 20, str = 71, },
}
itemBases["多刃锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 22, PhysicalMax = 36, CritChanceBase = 5, AttackRateBase = 1.3,  Range = 9,},
	req = { level = 24, str = 83, },
}
itemBases["祭礼之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 15%",
	weapon = { PhysicalMin = 32, PhysicalMax = 40, CritChanceBase = 5, AttackRateBase = 1.2, Range = 9, },
	req = { level = 28, str = 95, },
}
itemBases["梦境之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 21, PhysicalMax = 43, CritChanceBase = 5, AttackRateBase = 1.4,  Range = 9,},
	req = { level = 32, str = 107, },
}
itemBases["古龙之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "攻击速度提高 4%",
	weapon = { PhysicalMin = 28, PhysicalMax = 42, CritChanceBase = 5, AttackRateBase = 1.35, Range = 9, },
	req = { level = 34, str = 118, },
}
itemBases["坚石木棒"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 31, PhysicalMax = 51, CritChanceBase = 5, AttackRateBase = 1.25, Range = 9, },
	req = { level = 35, str = 116, },
}
itemBases["锐刺木棒"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 33, PhysicalMax = 42, CritChanceBase = 5, AttackRateBase = 1.4,  Range = 9,},
	req = { level = 38, str = 125, },
}
itemBases["破岩锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 15%",
	weapon = { PhysicalMin = 37, PhysicalMax = 69, CritChanceBase = 5, AttackRateBase = 1.15,  Range = 9,},
	req = { level = 41, str = 134, },
}
itemBases["强化战锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 25, PhysicalMax = 59, CritChanceBase = 5, AttackRateBase = 1.4,  Range = 9,},
	req = { level = 44, str = 143, },
}
itemBases["护体之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 38, PhysicalMax = 63, CritChanceBase = 5, AttackRateBase = 1.3,  Range = 9,},
	req = { level = 47, str = 152, },
}
itemBases["华丽之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 15%",
	weapon = { PhysicalMin = 53, PhysicalMax = 67, CritChanceBase = 5, AttackRateBase = 1.2,  Range = 9,},
	req = { level = 50, str = 161, },
}
itemBases["幻象之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 33, PhysicalMax = 69, CritChanceBase = 5, AttackRateBase = 1.4,  Range = 9,},
	req = { level = 53, str = 170, },
}
itemBases["龙之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "攻击速度提高 4%",
	weapon = { PhysicalMin = 44, PhysicalMax = 66, CritChanceBase = 5, AttackRateBase = 1.35,  Range = 9,},
	req = { level = 55, str = 184, },
}
itemBases["祖灵之杵"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 48, PhysicalMax = 80, CritChanceBase = 5, AttackRateBase = 1.25,  Range = 9,},
	req = { level = 56, str = 179, },
}
itemBases["裂肉之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 49, PhysicalMax = 62, CritChanceBase = 5, AttackRateBase = 1.4,  Range = 9,},
	req = { level = 58, str = 185, },
}
itemBases["坚锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 15%",
	weapon = { PhysicalMin = 54, PhysicalMax = 101, CritChanceBase = 5, AttackRateBase = 1.15, Range = 9, },
	req = { level = 60, str = 212, },
}
itemBases["军团之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 35, PhysicalMax = 81, CritChanceBase = 5, AttackRateBase = 1.4,  Range = 9,},
	req = { level = 62, str = 212, },
}
itemBases["锋刃重锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 49, PhysicalMax = 82, CritChanceBase = 5, AttackRateBase = 1.3,  Range = 9,},
	req = { level = 64, str = 212, },
}
itemBases["圣约之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 15%",
	weapon = { PhysicalMin = 65, PhysicalMax = 82, CritChanceBase = 5, AttackRateBase = 1.2,  Range = 9,},
	req = { level = 66, str = 212, },
}
itemBases["梦魇之锤"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, },
	implicit = "敌人晕眩门槛降低 10%",
	weapon = { PhysicalMin = 38, PhysicalMax = 80, CritChanceBase = 5, AttackRateBase = 1.4,  Range = 9,},
	req = { level = 68, str = 212, },
}
itemBases["巴哈姆特"] = {
	type = "One Handed Mace",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "攻击速度提高 6%",
	weapon = { PhysicalMin = 49, PhysicalMax = 74, CritChanceBase = 5, AttackRateBase = 1.35,  Range = 9,},
	req = { level = 70, str = 220, },
}

itemBases["朽木短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 10%",
	weapon = { PhysicalMin = 6, PhysicalMax = 9, CritChanceBase = 6, AttackRateBase = 1.4, Range = 9, },
	req = { str = 8, int = 8, },
}
itemBases["乌木短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 12%",
	weapon = { PhysicalMin = 8, PhysicalMax = 12, CritChanceBase = 6, AttackRateBase = 1.5,  Range = 9,},
	req = { level = 5, str = 14, int = 14, },
}
itemBases["铜锻短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 12%",
	weapon = { PhysicalMin = 12, PhysicalMax = 23, CritChanceBase = 6, AttackRateBase = 1.25, Range = 9, },
	req = { level = 10, str = 22, int = 22, },
}
itemBases["石英短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 20%",
	weapon = { PhysicalMin = 17, PhysicalMax = 26, CritChanceBase = 6.5, AttackRateBase = 1.25,  Range = 9,},
	req = { level = 15, str = 25, int = 35, },
}
itemBases["冷铁短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 14%",
	weapon = { PhysicalMin = 21, PhysicalMax = 32, CritChanceBase = 6, AttackRateBase = 1.25,  Range = 9,},
	req = { level = 20, str = 38, int = 38, },
}
itemBases["赤色短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 16%",
	weapon = { PhysicalMin = 17, PhysicalMax = 32, CritChanceBase = 6, AttackRateBase = 1.4,  Range = 9,},
	req = { level = 24, str = 44, int = 44, },
}
itemBases["祭仪短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 16%",
	weapon = { PhysicalMin = 21, PhysicalMax = 50, CritChanceBase = 6, AttackRateBase = 1.2,  Range = 9,},
	req = { level = 28, str = 51, int = 51, },
}
itemBases["影语短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 22%",
	weapon = { PhysicalMin = 29, PhysicalMax = 44, CritChanceBase = 6.2, AttackRateBase = 1.25, Range = 9, },
	req = { level = 32, str = 52, int = 62, },
}
itemBases["犄角短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, not_for_sale = true, maraketh = true, },
	implicit = "伤害穿透 4% 元素抗性",
	weapon = { PhysicalMin = 27, PhysicalMax = 50, CritChanceBase = 6, AttackRateBase = 1.3, Range = 9, },
	req = { level = 36, str = 66, int = 66, },
}
itemBases["远古之祭"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 18%",
	weapon = { PhysicalMin = 24, PhysicalMax = 36, CritChanceBase = 6, AttackRateBase = 1.5,  Range = 9,},
	req = { level = 35, str = 62, int = 62, },
}
itemBases["威能短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 18%",
	weapon = { PhysicalMin = 30, PhysicalMax = 55, CritChanceBase = 6, AttackRateBase = 1.25, Range = 9, },
	req = { level = 38, str = 67, int = 67, },
}
itemBases["水晶短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 30%",
	weapon = { PhysicalMin = 35, PhysicalMax = 52, CritChanceBase = 6.5, AttackRateBase = 1.25, Range = 9, },
	req = { level = 41, str = 59, int = 85, },
}
itemBases["铅铸短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 22%",
	weapon = { PhysicalMin = 38, PhysicalMax = 57, CritChanceBase = 6, AttackRateBase = 1.25,  Range = 9,},
	req = { level = 44, str = 77, int = 77, },
}
itemBases["血色短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 24%",
	weapon = { PhysicalMin = 30, PhysicalMax = 55, CritChanceBase = 6, AttackRateBase = 1.4, Range = 9, },
	req = { level = 47, str = 81, int = 81, },
}
itemBases["皇家短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 24%",
	weapon = { PhysicalMin = 34, PhysicalMax = 80, CritChanceBase = 6, AttackRateBase = 1.2,  Range = 9,},
	req = { level = 50, str = 86, int = 86, },
}
itemBases["深渊短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 30%",
	weapon = { PhysicalMin = 45, PhysicalMax = 67, CritChanceBase = 6.2, AttackRateBase = 1.25, Range = 9, },
	req = { level = 53, str = 83, int = 99, },
}
itemBases["灵鹿短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, not_for_sale = true, maraketh = true, },
	implicit = "伤害穿透 4% 元素抗性",
	weapon = { PhysicalMin = 39, PhysicalMax = 72, CritChanceBase = 6, AttackRateBase = 1.3, Range = 9, },
	req = { level = 55, str = 98, int = 98, },
}
itemBases["卡鲁短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 26%",
	weapon = { PhysicalMin = 37, PhysicalMax = 55, CritChanceBase = 6, AttackRateBase = 1.5, Range = 9, },
	req = { level = 56, str = 96, int = 96, },
}
itemBases["暴君之统"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 26%",
	weapon = { PhysicalMin = 43, PhysicalMax = 80, CritChanceBase = 6, AttackRateBase = 1.25, Range = 9, },
	req = { level = 58, str = 99, int = 99, },
}
itemBases["灵石短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 40%",
	weapon = { PhysicalMin = 49, PhysicalMax = 73, CritChanceBase = 6.5, AttackRateBase = 1.25,  Range = 9,},
	req = { level = 60, str = 95, int = 131, },
}
itemBases["白金短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 30%",
	weapon = { PhysicalMin = 51, PhysicalMax = 76, CritChanceBase = 6, AttackRateBase = 1.25, Range = 9, },
	req = { level = 62, str = 113, int = 113, },
}
itemBases["瓦尔短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 32%",
	weapon = { PhysicalMin = 37, PhysicalMax = 70, CritChanceBase = 6, AttackRateBase = 1.4, Range = 9, },
	req = { level = 64, str = 113, int = 113, },
}
itemBases["禁礼短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 32%",
	weapon = { PhysicalMin = 41, PhysicalMax = 95, CritChanceBase = 6, AttackRateBase = 1.2,  Range = 9,},
	req = { level = 66, str = 113, int = 113, },
}
itemBases["虚影短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, },
	implicit = "元素伤害提高 40%",
	weapon = { PhysicalMin = 50, PhysicalMax = 76, CritChanceBase = 6.2, AttackRateBase = 1.25,  Range = 9,},
	req = { level = 68, str = 104, int = 122, },
}
itemBases["恶魔短杖"] = {
	type = "Sceptre",
	socketLimit = 3,
	tags = { default = true, weapon = true, onehand = true, mace = true, one_hand_weapon = true, sceptre = true, not_for_sale = true, maraketh = true, },
	implicit = "伤害穿透 6% 元素抗性",
	weapon = { PhysicalMin = 42, PhysicalMax = 78, CritChanceBase = 6, AttackRateBase = 1.3, Range = 9, },
	req = { level = 70, str = 121, int = 113, },
}

itemBases["朽木巨锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 9, PhysicalMax = 13, CritChanceBase = 5, AttackRateBase = 1.3, Range = 11,  },
	req = { str = 20, },
}
itemBases["祭仪巨锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 15, PhysicalMax = 23, CritChanceBase = 5, AttackRateBase = 1.2,  Range = 11, },
	req = { level = 8, str = 35, },
}
itemBases["千斤锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 15, PhysicalMax = 30, CritChanceBase = 5, AttackRateBase = 1.25, Range = 11,  },
	req = { level = 12, str = 47, },
}
itemBases["冷铁重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 45%",
	weapon = { PhysicalMin = 21, PhysicalMax = 32, CritChanceBase = 5, AttackRateBase = 1.3,  Range = 11, },
	req = { level = 17, str = 62, },
}
itemBases["狼牙重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 24, PhysicalMax = 45, CritChanceBase = 5, AttackRateBase = 1.25,  Range = 11, },
	req = { level = 22, str = 77, },
}
itemBases["铜影巨锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 34, PhysicalMax = 51, CritChanceBase = 5, AttackRateBase = 1.2, Range = 11,  },
	req = { level = 27, str = 92, },
}
itemBases["恐惧重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 39, PhysicalMax = 53, CritChanceBase = 5, AttackRateBase = 1.25, Range = 11,  },
	req = { level = 32, str = 107, },
}
itemBases["晨星"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "范围效果扩大 4%",
	weapon = { PhysicalMin = 39, PhysicalMax = 58, CritChanceBase = 5, AttackRateBase = 1.25,  Range = 11, },
	req = { level = 34, str = 118, },
}
itemBases["图腾巨锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 49, PhysicalMax = 73, CritChanceBase = 5, AttackRateBase = 1.1,  Range = 11, },
	req = { level = 36, str = 119, },
}
itemBases["刚猛巨锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 37, PhysicalMax = 76, CritChanceBase = 5, AttackRateBase = 1.25,  Range = 11, },
	req = { level = 40, str = 131, },
}
itemBases["沉钢重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 45%",
	weapon = { PhysicalMin = 47, PhysicalMax = 70, CritChanceBase = 5, AttackRateBase = 1.3,  Range = 11, },
	req = { level = 44, str = 143, },
}
itemBases["凶刺巨锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 47, PhysicalMax = 88, CritChanceBase = 5, AttackRateBase = 1.25, Range = 11,  },
	req = { level = 48, str = 155, },
}
itemBases["华丽重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 62, PhysicalMax = 92, CritChanceBase = 5, AttackRateBase = 1.2,  Range = 11, },
	req = { level = 51, str = 164, },
}
itemBases["威权巨锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 66, PhysicalMax = 89, CritChanceBase = 5, AttackRateBase = 1.25,  Range = 11, },
	req = { level = 54, str = 173, },
}
itemBases["日光锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "范围效果扩大 4%",
	weapon = { PhysicalMin = 64, PhysicalMax = 97, CritChanceBase = 5, AttackRateBase = 1.25,  Range = 11, },
	req = { level = 56, str = 187, },
}
itemBases["卡鲁重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 79, PhysicalMax = 118, CritChanceBase = 5, AttackRateBase = 1.1,  Range = 11, },
	req = { level = 57, str = 182, },
}
itemBases["巨型重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 57, PhysicalMax = 118, CritChanceBase = 5, AttackRateBase = 1.25,  Range = 11, },
	req = { level = 59, str = 188, },
}
itemBases["扫荡者"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 45%",
	weapon = { PhysicalMin = 67, PhysicalMax = 100, CritChanceBase = 5, AttackRateBase = 1.3,  Range = 11, },
	req = { level = 61, str = 212, },
}
itemBases["戮魂重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 63, PhysicalMax = 117, CritChanceBase = 5, AttackRateBase = 1.25,  Range = 11, },
	req = { level = 63, str = 212, },
}
itemBases["帝国重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 74, PhysicalMax = 111, CritChanceBase = 5, AttackRateBase = 1.2,  Range = 11, },
	req = { level = 65, str = 212, },
}
itemBases["惧灵重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, },
	implicit = "敌人被晕眩时间延长 30%",
	weapon = { PhysicalMin = 75, PhysicalMax = 102, CritChanceBase = 5, AttackRateBase = 1.25,  Range = 11, },
	req = { level = 67, str = 212, },
}
itemBases["花冠重锤"] = {
	type = "Two Handed Mace",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, mace = true, two_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "范围效果扩大 6%",
	weapon = { PhysicalMin = 74, PhysicalMax = 110, CritChanceBase = 5, AttackRateBase = 1.25,  Range = 11, },
	req = { level = 69, str = 220, },
}
