-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["朽木之干"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, small_staff = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 8, PhysicalMax = 17, CritChanceBase = 6, AttackRateBase = 1.3, Range = 11, },
	req = { str = 12, int = 12, },
}
itemBases["粗制长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 9, PhysicalMax = 28, CritChanceBase = 6.2, AttackRateBase = 1.25, Range = 11, },
	req = { level = 9, str = 20, int = 20, },
}
itemBases["长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 17, PhysicalMax = 28, CritChanceBase = 6, AttackRateBase = 1.3, Range = 11, },
	req = { level = 13, str = 27, int = 27, },
}
itemBases["铁锻长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 16, PhysicalMax = 47, CritChanceBase = 6.4, AttackRateBase = 1.2, Range = 11, },
	req = { level = 18, str = 35, int = 35, },
}
itemBases["强化长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +20%",
	weapon = { PhysicalMin = 23, PhysicalMax = 48, CritChanceBase = 6, AttackRateBase = 1.2,  Range = 11,},
	req = { level = 23, str = 43, int = 43, },
}
itemBases["皇家长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 23, PhysicalMax = 70, CritChanceBase = 6.5, AttackRateBase = 1.15,  Range = 11,},
	req = { level = 28, str = 51, int = 51, },
}
itemBases["毒牙长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 33, PhysicalMax = 62, CritChanceBase = 6.1, AttackRateBase = 1.25,  Range = 11,},
	req = { level = 33, str = 59, int = 59, },
}
itemBases["新月长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "攻击和法术暴击率提高 80%",
	weapon = { PhysicalMin = 35, PhysicalMax = 73, CritChanceBase = 6, AttackRateBase = 1.2,  Range = 11,},
	req = { level = 36, str = 66, int = 66, },
}
itemBases["坚木长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 29, PhysicalMax = 88, CritChanceBase = 6.2, AttackRateBase = 1.15, Range = 11, },
	req = { level = 37, str = 65, int = 65, },
}
itemBases["细柄长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 41, PhysicalMax = 68, CritChanceBase = 6, AttackRateBase = 1.3,  Range = 11,},
	req = { level = 41, str = 72, int = 72, },
}
itemBases["军用长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 34, PhysicalMax = 101, CritChanceBase = 6.4, AttackRateBase = 1.2,  Range = 11,},
	req = { level = 45, str = 78, int = 78, },
}
itemBases["蛇纹长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +20%",
	weapon = { PhysicalMin = 46, PhysicalMax = 95, CritChanceBase = 6, AttackRateBase = 1.2,  Range = 11,},
	req = { level = 49, str = 85, int = 85, },
}
itemBases["贵族长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 42, PhysicalMax = 125, CritChanceBase = 6.5, AttackRateBase = 1.15, Range = 11, },
	req = { level = 52, str = 89, int = 89, },
}
itemBases["恶灵长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 55, PhysicalMax = 103, CritChanceBase = 6.1, AttackRateBase = 1.25, Range = 11, },
	req = { level = 55, str = 94, int = 94, },
}
itemBases["月神长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "攻击和法术暴击率提高 80%",
	weapon = { PhysicalMin = 57, PhysicalMax = 118, CritChanceBase = 6, AttackRateBase = 1.2,  Range = 11,},
	req = { level = 57, str = 101, int = 101, },
}
itemBases["史典长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 47, PhysicalMax = 141, CritChanceBase = 6.2, AttackRateBase = 1.15, Range = 11, },
	req = { level = 58, str = 99, int = 99, },
}
itemBases["武术长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 62, PhysicalMax = 103, CritChanceBase = 6, AttackRateBase = 1.3, Range = 11, },
	req = { level = 60, str = 113, int = 113, },
}
itemBases["艾兹麦长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 46, PhysicalMax = 138, CritChanceBase = 6.4, AttackRateBase = 1.2,  Range = 11,},
	req = { level = 62, str = 113, int = 113, },
}
itemBases["风暴长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +20%",
	weapon = { PhysicalMin = 57, PhysicalMax = 119, CritChanceBase = 6, AttackRateBase = 1.2,  Range = 11,},
	req = { level = 64, str = 113, int = 113, },
}
itemBases["帝国长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 49, PhysicalMax = 147, CritChanceBase = 6.5, AttackRateBase = 1.15,  Range = 11,},
	req = { level = 66, str = 113, int = 113, },
}
itemBases["审判长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, },
	implicit = "持长杖时攻击伤害格挡几率 +18%",
	weapon = { PhysicalMin = 61, PhysicalMax = 113, CritChanceBase = 6.1, AttackRateBase = 1.25, Range = 11, },
	req = { level = 68, str = 113, int = 113, },
}
itemBases["月蚀长杖"] = {
	type = "Staff",
	socketLimit = 6,
	tags = { default = true, weapon = true, twohand = true, staff = true, two_hand_weapon = true, not_for_sale = true, maraketh = true, },
	implicit = "攻击和法术暴击率提高 100%",
	weapon = { PhysicalMin = 60, PhysicalMax = 125, CritChanceBase = 6, AttackRateBase = 1.2,  Range = 11,},
	req = { level = 70, str = 117, int = 117, },
}
