-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["赤红珠宝"] = {
	type = "Jewel",
	tags = { default = true, jewel = true, not_dex = true, not_int = true, not_for_sale = true, strjewel = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["翠绿珠宝"] = {
	type = "Jewel",
	tags = { default = true, jewel = true, not_str = true, not_int = true, not_for_sale = true, dexjewel = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["钴蓝珠宝"] = {
	type = "Jewel",
	tags = { default = true, jewel = true, not_dex = true, not_str = true, not_for_sale = true, intjewel = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["三相珠宝"] = {
	type = "Jewel",
	tags = { default = true, jewel = true, intjewel = true, dexjewel = true, strjewel = true, not_for_sale = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["三相珠宝"] = {
	type = "Jewel",
	tags = { default = true, jewel = true, intjewel = true, dexjewel = true, strjewel = true, not_for_sale = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["永恒珠宝"] = {
	type = "Jewel",
	tags = { default = true, jewel = true, intjewel = true, dexjewel = true, strjewel = true, not_for_sale = true, },
	implicitModTypes = { {  }, },
	req = { },
}

itemBases["苍白之凝珠宝"] = {
	type = "Jewel",
	subType = "Abyss",
	tags = { default = true, not_for_sale = true, abyss_jewel_summoner = true, abyss_jewel = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["安睡之凝珠宝"] = {
	type = "Jewel",
	subType = "Abyss",
	tags = { default = true, not_for_sale = true, abyss_jewel_caster = true, abyss_jewel = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["凶残之凝珠宝"] = {
	type = "Jewel",
	subType = "Abyss",
	tags = { default = true, not_for_sale = true, abyss_jewel_melee = true, abyss_jewel = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["锐利之凝珠宝"] = {
	type = "Jewel",
	subType = "Abyss",
	tags = { default = true, not_for_sale = true, abyss_jewel_ranged = true, abyss_jewel = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["大型星团珠宝"] = {
	type = "Jewel",
	subType = "Cluster",
	tags = { default = true, jewel = true, not_for_sale = true, expansion_jewel_large = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["中型星团珠宝"] = {
	type = "Jewel",
	subType = "Cluster",
	tags = { default = true, jewel = true, not_for_sale = true, expansion_jewel_medium = true, },
	implicitModTypes = { {  }, },
	req = { },
}
itemBases["小型星团珠宝"] = {
	type = "Jewel",
	subType = "Cluster",
	tags = { default = true, jewel = true, not_for_sale = true, expansion_jewel_small = true, },
	implicitModTypes = { {  }, },
	req = { },
}