-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Glove enchantment skills
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...

skills["EnchantmentOfBladesOnHit"] = {
	name = "刀锋之誓",
	hidden = true,
	color = 4,
	description = "发射一连串的虚空飞刀. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [3] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 7), 
		skill("cooldown", 5), 
		skill("PhysicalMin", 79), --"spell_minimum_base_physical_damage" = 79
		skill("PhysicalMax", 126), --"spell_maximum_base_physical_damage" = 126
		mod("ChainCountMax", "BASE", 3), --"number_of_additional_projectiles_in_chain" = 3
		--"cast_on_hit_%" = 100
		--"skill_art_variation" = 0
		mod("ProjectileCount", "BASE", 2), --"number_of_additional_projectiles" = 2
		--"base_is_projectile" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfBladesOnHit2"] = {
	name = "刀锋之律",
	hidden = true,
	color = 4,
	description = "发射一连串的虚空飞刀. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [3] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 7), 
		skill("cooldown", 5), 
		skill("PhysicalMin", 381), --"spell_minimum_base_physical_damage" = 381
		skill("PhysicalMax", 585), --"spell_maximum_base_physical_damage" = 585
		mod("ChainCountMax", "BASE", 3), --"number_of_additional_projectiles_in_chain" = 3
		--"cast_on_hit_%" = 100
		--"skill_art_variation" = 0
		mod("ProjectileCount", "BASE", 2), --"number_of_additional_projectiles" = 2
		--"base_is_projectile" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfBladesOnHit3"] = {
	name = "刀锋之令",
	hidden = true,
	color = 4,
	description = "发射一连串的虚空飞刀. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [3] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 7), 
		skill("cooldown", 5), 
		skill("PhysicalMin", 985), --"spell_minimum_base_physical_damage" = 985
		skill("PhysicalMax", 1477), --"spell_maximum_base_physical_damage" = 1477
		mod("ChainCountMax", "BASE", 3), --"number_of_additional_projectiles_in_chain" = 3
		--"cast_on_hit_%" = 100
		--"skill_art_variation" = 0
		mod("ProjectileCount", "BASE", 2), --"number_of_additional_projectiles" = 2
		--"base_is_projectile" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfBladesOnHit4"] = {
	name = "刀锋之诫",
	hidden = true,
	color = 4,
	description = "发射一连串的虚空飞刀. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [3] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 7), 
		skill("cooldown", 5), 
		skill("PhysicalMin", 1833), --"spell_minimum_base_physical_damage" = 1833
		skill("PhysicalMax", 2903), --"spell_maximum_base_physical_damage" = 2903
		mod("ChainCountMax", "BASE", 4), --"number_of_additional_projectiles_in_chain" = 4
		--"cast_on_hit_%" = 100
		--"skill_art_variation" = 0
		mod("ProjectileCount", "BASE", 2), --"number_of_additional_projectiles" = 2
		--"base_is_projectile" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfFlamesOnHit"] = {
	name = "烈火之誓",
	hidden = true,
	color = 4,
	description = "释放一个火焰的新星, 有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [10] = true, [33] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 5), 
		skill("FireMin", 93), --"spell_minimum_base_fire_damage" = 93
		skill("FireMax", 140), --"spell_maximum_base_fire_damage" = 140
		--"cast_on_hit_%" = 100
		--"is_area_damage" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfFlamesOnHit2"] = {
	name = "烈火之律",
	hidden = true,
	color = 4,
	description = "释放一个火焰的新星, 有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [10] = true, [33] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 5), 
		skill("FireMin", 409), --"spell_minimum_base_fire_damage" = 409
		skill("FireMax", 601), --"spell_maximum_base_fire_damage" = 601
		--"cast_on_hit_%" = 100
		--"is_area_damage" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfFlamesOnHit3"] = {
	name = "烈火之令",
	hidden = true,
	color = 4,
	description = "释放一个火焰的新星, 有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [10] = true, [33] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 5), 
		skill("FireMin", 999), --"spell_minimum_base_fire_damage" = 999
		skill("FireMax", 1453), --"spell_maximum_base_fire_damage" = 1453
		--"cast_on_hit_%" = 100
		--"is_area_damage" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfFlamesOnHit4"] = {
	name = "烈火之诫",
	hidden = true,
	color = 4,
	description = "释放一个火焰的新星, 有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [10] = true, [33] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 5), 
		skill("FireMin", 1800), --"spell_minimum_base_fire_damage" = 1800
		skill("FireMax", 2770), --"spell_maximum_base_fire_damage" = 2770
		--"cast_on_hit_%" = 100
		--"is_area_damage" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfForceOnHit"] = {
	name = "原力之誓",
	hidden = true,
	color = 4,
	description = "对你面前的敌人们造成普通攻击的伤害. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [11] = true, [10] = true, [47] = true, [57] = true, },
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 1.35), 
		skill("baseMultiplier", 1.35), 
		skill("cooldown", 5), 
		--"attack_trigger_on_hit_%" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfForceOnHit2"] = {
	name = "原力之律",
	hidden = true,
	color = 4,
	description = "对你面前的敌人们造成普通攻击的伤害. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [11] = true, [10] = true, [47] = true, [57] = true, },
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 1.89), 
		skill("baseMultiplier", 1.89), 
		skill("cooldown", 5), 
		--"attack_trigger_on_hit_%" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfForceOnHit3"] = {
	name = "原力之令",
	hidden = true,
	color = 4,
	description = "对你面前的敌人们造成普通攻击的伤害. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [11] = true, [10] = true, [47] = true, [57] = true, },
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 2.43), 
		skill("baseMultiplier", 2.43), 
		skill("cooldown", 5), 
		--"attack_trigger_on_hit_%" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfForceOnHit4"] = {
	name = "原力之诫",
	hidden = true,
	color = 4,
	description = "对你面前的敌人们造成普通攻击的伤害. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [11] = true, [10] = true, [47] = true, [57] = true, },
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 2.97), 
		skill("baseMultiplier", 2.97), 
		skill("cooldown", 5), 
		--"attack_trigger_on_hit_%" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfFrostOnKill"] = {
	name = "寒冰之誓",
	hidden = true,
	color = 4,
	description = "制造一个寒冰投射物的新星. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [3] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 5), 
		skill("ColdMin", 72), --"spell_minimum_base_cold_damage" = 72
		skill("ColdMax", 114), --"spell_maximum_base_cold_damage" = 114
		--"skill_art_variation" = 1
		--"chance_to_cast_on_kill_%_target_self" = 100
		mod("ProjectileCount", "BASE", 8), --"number_of_additional_projectiles" = 8
		--"base_is_projectile" = ?
		--"projectiles_nova" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfFrostOnKill2"] = {
	name = "寒冰之律",
	hidden = true,
	color = 4,
	description = "制造一个寒冰投射物的新星. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [3] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 5), 
		skill("ColdMin", 332), --"spell_minimum_base_cold_damage" = 332
		skill("ColdMax", 509), --"spell_maximum_base_cold_damage" = 509
		--"skill_art_variation" = 1
		--"chance_to_cast_on_kill_%_target_self" = 100
		mod("ProjectileCount", "BASE", 8), --"number_of_additional_projectiles" = 8
		--"base_is_projectile" = ?
		--"projectiles_nova" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfFrostOnKill3"] = {
	name = "寒冰之令",
	hidden = true,
	color = 4,
	description = "制造一个寒冰投射物的新星. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [3] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 5), 
		skill("ColdMin", 836), --"spell_minimum_base_cold_damage" = 836
		skill("ColdMax", 1254), --"spell_maximum_base_cold_damage" = 1254
		--"skill_art_variation" = 1
		--"chance_to_cast_on_kill_%_target_self" = 100
		mod("ProjectileCount", "BASE", 8), --"number_of_additional_projectiles" = 8
		--"base_is_projectile" = ?
		--"projectiles_nova" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfFrostOnKill4"] = {
	name = "寒冰之诫",
	hidden = true,
	color = 4,
	description = "制造一个寒冰投射物的新星. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [3] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 5), 
		skill("ColdMin", 1530), --"spell_minimum_base_cold_damage" = 1530
		skill("ColdMax", 2422), --"spell_maximum_base_cold_damage" = 2422
		--"skill_art_variation" = 1
		--"chance_to_cast_on_kill_%_target_self" = 100
		mod("ProjectileCount", "BASE", 8), --"number_of_additional_projectiles" = 8
		--"base_is_projectile" = ?
		--"projectiles_nova" = ?
		skill("triggered", true, { type = "SkillType", skillType = SkillType.TriggerableSpell }), --"spell_uncastable_if_triggerable" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfFuryOnHit"] = {
	name = "狂怒之誓",
	hidden = true,
	color = 4,
	description = "发射一个定必穿透敌人的你的武器的复制品或是投射物的投射物. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [48] = true, [3] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 1.5), 
		skill("baseMultiplier", 1.5), 
		skill("cooldown", 5), 
		--"attack_trigger_on_hit_%" = 100
		--"projectile_spiral_nova_time_ms" = 800
		--"projectile_spiral_nova_angle" = 180
		--"base_number_of_projectiles_in_spiral_nova" = 10
		--"skill_art_variation" = 1
		mod("SkillPhysicalDamageConvertToFire", "BASE", 50), --"skill_physical_damage_%_to_convert_to_fire" = 50
		--"projectile_spiral_nova_starting_angle_offset" = -90
		mod("PierceCount", "BASE", 2), --"projectile_base_number_of_targets_to_pierce" = 2
		--"base_is_projectile" = ?
		--"skill_can_fire_arrows" = ?
		--"skill_can_fire_wand_projectiles" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfFuryOnHit2"] = {
	name = "狂怒之律",
	hidden = true,
	color = 4,
	description = "发射一个定必穿透敌人的你的武器的复制品或是投射物的投射物. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [48] = true, [3] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 2.1), 
		skill("baseMultiplier", 2.1), 
		skill("cooldown", 5), 
		--"attack_trigger_on_hit_%" = 100
		--"projectile_spiral_nova_time_ms" = 800
		--"projectile_spiral_nova_angle" = 180
		--"base_number_of_projectiles_in_spiral_nova" = 10
		--"skill_art_variation" = 1
		mod("SkillPhysicalDamageConvertToFire", "BASE", 50), --"skill_physical_damage_%_to_convert_to_fire" = 50
		--"projectile_spiral_nova_starting_angle_offset" = -90
		mod("PierceCount", "BASE", 3), --"projectile_base_number_of_targets_to_pierce" = 3
		--"base_is_projectile" = ?
		--"skill_can_fire_arrows" = ?
		--"skill_can_fire_wand_projectiles" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfFuryOnHit3"] = {
	name = "狂怒之令",
	hidden = true,
	color = 4,
	description = "发射一个定必穿透敌人的你的武器的复制品或是投射物的投射物. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [48] = true, [3] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 2.7), 
		skill("baseMultiplier", 2.7), 
		skill("cooldown", 5), 
		--"attack_trigger_on_hit_%" = 100
		--"projectile_spiral_nova_time_ms" = 800
		--"projectile_spiral_nova_angle" = 180
		--"base_number_of_projectiles_in_spiral_nova" = 10
		--"skill_art_variation" = 1
		mod("SkillPhysicalDamageConvertToFire", "BASE", 50), --"skill_physical_damage_%_to_convert_to_fire" = 50
		--"projectile_spiral_nova_starting_angle_offset" = -90
		mod("PierceCount", "BASE", 4), --"projectile_base_number_of_targets_to_pierce" = 4
		--"base_is_projectile" = ?
		--"skill_can_fire_arrows" = ?
		--"skill_can_fire_wand_projectiles" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfFuryOnHit4"] = {
	name = "狂怒之诫",
	hidden = true,
	color = 4,
	description = "发射一个定必穿透敌人的你的武器的复制品或是投射物的投射物. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [48] = true, [3] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 3.3), 
		skill("baseMultiplier", 3.3), 
		skill("cooldown", 5), 
		--"attack_trigger_on_hit_%" = 100
		--"projectile_spiral_nova_time_ms" = 800
		--"projectile_spiral_nova_angle" = 180
		--"base_number_of_projectiles_in_spiral_nova" = 10
		--"skill_art_variation" = 1
		mod("SkillPhysicalDamageConvertToFire", "BASE", 50), --"skill_physical_damage_%_to_convert_to_fire" = 50
		--"projectile_spiral_nova_starting_angle_offset" = -90
		mod("PierceCount", "BASE", 5), --"projectile_base_number_of_targets_to_pierce" = 5
		--"base_is_projectile" = ?
		--"skill_can_fire_arrows" = ?
		--"skill_can_fire_wand_projectiles" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfInfernoOnKill"] = {
	name = "炼狱之誓",
	hidden = true,
	color = 4,
	description = "从天上降下一颗陨石. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [33] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 10), 
		skill("FireMin", 155), --"spell_minimum_base_fire_damage" = 155
		skill("FireMax", 249), --"spell_maximum_base_fire_damage" = 249
		skill("duration", 2), --"base_skill_effect_duration" = 2000
		--"fire_storm_fireball_delay_ms" = 100
		--"skill_override_pvp_scaling_time_ms" = 450
		--"chance_to_cast_on_kill_%_target_self" = 100
		skill("showAverage", true), --"base_skill_show_average_damage_instead_of_dps" = ?
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfInfernoOnKill2"] = {
	name = "炼狱之律",
	hidden = true,
	color = 4,
	description = "从天上降下一颗陨石. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [33] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 10), 
		skill("FireMin", 722), --"spell_minimum_base_fire_damage" = 722
		skill("FireMax", 1107), --"spell_maximum_base_fire_damage" = 1107
		skill("duration", 2), --"base_skill_effect_duration" = 2000
		--"fire_storm_fireball_delay_ms" = 100
		--"skill_override_pvp_scaling_time_ms" = 450
		--"chance_to_cast_on_kill_%_target_self" = 100
		skill("showAverage", true), --"base_skill_show_average_damage_instead_of_dps" = ?
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfInfernoOnKill3"] = {
	name = "炼狱之令",
	hidden = true,
	color = 4,
	description = "从天上降下一颗陨石. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [33] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 10), 
		skill("FireMin", 1817), --"spell_minimum_base_fire_damage" = 1817
		skill("FireMax", 2725), --"spell_maximum_base_fire_damage" = 2725
		skill("duration", 2), --"base_skill_effect_duration" = 2000
		--"fire_storm_fireball_delay_ms" = 100
		--"skill_override_pvp_scaling_time_ms" = 450
		--"chance_to_cast_on_kill_%_target_self" = 100
		skill("showAverage", true), --"base_skill_show_average_damage_instead_of_dps" = ?
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfInfernoOnKill4"] = {
	name = "炼狱之诫",
	hidden = true,
	color = 4,
	description = "从天上降下一颗陨石. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [33] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 10), 
		skill("FireMin", 3324), --"spell_minimum_base_fire_damage" = 3324
		skill("FireMax", 5263), --"spell_maximum_base_fire_damage" = 5263
		skill("duration", 2), --"base_skill_effect_duration" = 2000
		--"fire_storm_fireball_delay_ms" = 100
		--"skill_override_pvp_scaling_time_ms" = 450
		--"chance_to_cast_on_kill_%_target_self" = 100
		skill("showAverage", true), --"base_skill_show_average_damage_instead_of_dps" = ?
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfIreWhenHit"] = {
	name = "雷霆之誓",
	hidden = true,
	color = 2,
	description = "复制并释放出一个你所使用的武器或其投射物, 并带有闪电在一个定点旋转, 对区域中的敌人造成伤害. 有 10 秒冷却时间. ",
	skillTypes = { [1] = true, [10] = true, [11] = true, [12] = true, [18] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 0.5), 
		skill("damageEffectiveness", 0.6), 
		skill("baseMultiplier", 0.6), 
		skill("cooldown", 10), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"extra_gore_chance_override_%" = 30
		--"melee_counterattack_trigger_on_hit_%" = 100
		mod("SkillPhysicalDamageConvertToLightning", "BASE", 50), --"skill_physical_damage_%_to_convert_to_lightning" = 50
		--"is_area_damage" = ?
		--"attack_unusable_if_triggerable" = ?
		--"attack_is_not_melee_override" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfIreWhenHit2"] = {
	name = "雷霆之律",
	hidden = true,
	color = 2,
	description = "复制并释放出一个你所使用的武器或其投射物, 并带有闪电在一个定点旋转, 对区域中的敌人造成伤害. 有 10 秒冷却时间. ",
	skillTypes = { [1] = true, [10] = true, [11] = true, [12] = true, [18] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 0.5), 
		skill("damageEffectiveness", 0.9), 
		skill("baseMultiplier", 0.9), 
		skill("cooldown", 10), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"extra_gore_chance_override_%" = 30
		--"melee_counterattack_trigger_on_hit_%" = 100
		mod("SkillPhysicalDamageConvertToLightning", "BASE", 50), --"skill_physical_damage_%_to_convert_to_lightning" = 50
		--"is_area_damage" = ?
		--"attack_unusable_if_triggerable" = ?
		--"attack_is_not_melee_override" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfIreWhenHit3"] = {
	name = "雷霆之令",
	hidden = true,
	color = 2,
	description = "复制并释放出一个你所使用的武器或其投射物, 并带有闪电在一个定点旋转, 对区域中的敌人造成伤害. 有 10 秒冷却时间. ",
	skillTypes = { [1] = true, [10] = true, [11] = true, [12] = true, [18] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 0.5), 
		skill("damageEffectiveness", 1.2), 
		skill("baseMultiplier", 1.2), 
		skill("cooldown", 10), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"extra_gore_chance_override_%" = 30
		--"melee_counterattack_trigger_on_hit_%" = 100
		mod("SkillPhysicalDamageConvertToLightning", "BASE", 50), --"skill_physical_damage_%_to_convert_to_lightning" = 50
		--"is_area_damage" = ?
		--"attack_unusable_if_triggerable" = ?
		--"attack_is_not_melee_override" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfIreWhenHit4"] = {
	name = "雷霆之诫",
	hidden = true,
	color = 2,
	description = "复制并释放出一个你所使用的武器或其投射物, 并带有闪电在一个定点旋转, 对区域中的敌人造成伤害. 有 10 秒冷却时间. ",
	skillTypes = { [1] = true, [10] = true, [11] = true, [12] = true, [18] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 0.5), 
		skill("damageEffectiveness", 1.5), 
		skill("baseMultiplier", 1.5), 
		skill("cooldown", 10), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"extra_gore_chance_override_%" = 30
		--"melee_counterattack_trigger_on_hit_%" = 100
		mod("SkillPhysicalDamageConvertToLightning", "BASE", 50), --"skill_physical_damage_%_to_convert_to_lightning" = 50
		--"is_area_damage" = ?
		--"attack_unusable_if_triggerable" = ?
		--"attack_is_not_melee_override" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfLightWhenCrit"] = {
	name = "光之誓",
	hidden = true,
	color = 4,
	description = "在你的四周制造奉献地面, 并造成一定比例的主手武器伤害. 奉献地面增加你和你的队友额外生命回复. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [11] = true, [12] = true, [7] = true, [47] = true, [57] = true, },
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 1.35), 
		skill("baseMultiplier", 1.35), 
		skill("cooldown", 5), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		mod("LifeRegenPercent", "BASE", 6, 0, 0, nil), --"life_regeneration_rate_per_minute_%" = 360
		--"attack_trigger_when_critically_hit_%" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfLightWhenCrit2"] = {
	name = "光之律",
	hidden = true,
	color = 4,
	description = "在你的四周制造奉献地面, 并造成一定比例的主手武器伤害. 奉献地面增加你和你的队友额外生命回复. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [11] = true, [12] = true, [7] = true, [47] = true, [57] = true, },
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 1.89), 
		skill("baseMultiplier", 1.89), 
		skill("cooldown", 5), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		mod("LifeRegenPercent", "BASE", 6, 0, 0, nil), --"life_regeneration_rate_per_minute_%" = 360
		--"attack_trigger_when_critically_hit_%" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfLightWhenCrit3"] = {
	name = "光之令",
	hidden = true,
	color = 4,
	description = "在你的四周制造奉献地面, 并造成一定比例的主手武器伤害. 奉献地面增加你和你的队友额外生命回复. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [11] = true, [12] = true, [7] = true, [47] = true, [57] = true, },
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 2.43), 
		skill("baseMultiplier", 2.43), 
		skill("cooldown", 5), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		mod("LifeRegenPercent", "BASE", 6, 0, 0, nil), --"life_regeneration_rate_per_minute_%" = 360
		--"attack_trigger_when_critically_hit_%" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfLightWhenCrit4"] = {
	name = "光之诫",
	hidden = true,
	color = 4,
	description = "在你的四周制造奉献地面, 并造成一定比例的主手武器伤害. 奉献地面增加你和你的队友额外生命回复. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [11] = true, [12] = true, [7] = true, [47] = true, [57] = true, },
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 2.97), 
		skill("baseMultiplier", 2.97), 
		skill("cooldown", 5), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		mod("LifeRegenPercent", "BASE", 6, 0, 0, nil), --"life_regeneration_rate_per_minute_%" = 360
		--"attack_trigger_when_critically_hit_%" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfReflectionWhenHit"] = {
	name = "倒影之誓",
	hidden = true,
	color = 4,
	description = "制造一个与你使用同样武器的复制体. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [9] = true, [21] = true, [42] = true, [12] = true, [36] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [3] = true, [68] = true, [28] = true, },
	minionList = {
		"Clone",
	},
	minionUses = {
		["Weapon 1"] = true,
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 10), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"number_of_monsters_to_summon" = 1
		mod("MinionModifier", "LIST", { mod = mod("Damage", "INC", 80) }), --"minion_damage_+%" = 80
		mod("MinionModifier", "LIST", { mod = mod("Life", "INC", 150) }), --"minion_maximum_life_+%" = 150
		--"display_minion_monster_type" = 4
		skill("minionLevel", 32), --"display_minion_monster_level" = 32
		--"cast_when_hit_%" = 100
		mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", 100) }), --"active_skill_minion_damage_+%_final" = 100
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfReflectionWhenHit2"] = {
	name = "倒影之律",
	hidden = true,
	color = 4,
	description = "制造一个与你使用同样武器的复制体. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [9] = true, [21] = true, [42] = true, [12] = true, [36] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [3] = true, [68] = true, [28] = true, },
	minionList = {
		"Clone",
	},
	minionUses = {
		["Weapon 1"] = true,
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 10), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"number_of_monsters_to_summon" = 1
		mod("MinionModifier", "LIST", { mod = mod("Damage", "INC", 100) }), --"minion_damage_+%" = 100
		mod("MinionModifier", "LIST", { mod = mod("Life", "INC", 150) }), --"minion_maximum_life_+%" = 150
		--"display_minion_monster_type" = 4
		skill("minionLevel", 53), --"display_minion_monster_level" = 53
		--"cast_when_hit_%" = 100
		mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", 200) }), --"active_skill_minion_damage_+%_final" = 200
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfReflectionWhenHit3"] = {
	name = "倒影之令",
	hidden = true,
	color = 4,
	description = "制造一个与你使用同样武器的复制体. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [9] = true, [21] = true, [42] = true, [12] = true, [36] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [3] = true, [68] = true, [28] = true, },
	minionList = {
		"Clone",
	},
	minionUses = {
		["Weapon 1"] = true,
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 10), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"number_of_monsters_to_summon" = 1
		mod("MinionModifier", "LIST", { mod = mod("Damage", "INC", 120) }), --"minion_damage_+%" = 120
		mod("MinionModifier", "LIST", { mod = mod("Life", "INC", 150) }), --"minion_maximum_life_+%" = 150
		--"display_minion_monster_type" = 4
		skill("minionLevel", 66), --"display_minion_monster_level" = 66
		--"cast_when_hit_%" = 100
		mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", 300) }), --"active_skill_minion_damage_+%_final" = 300
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfReflectionWhenHit4"] = {
	name = "倒影之诫",
	hidden = true,
	color = 4,
	description = "制造一个与你使用同样武器的复制体. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [9] = true, [21] = true, [42] = true, [12] = true, [36] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [3] = true, [68] = true, [28] = true, },
	minionList = {
		"Clone",
	},
	minionUses = {
		["Weapon 1"] = true,
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 10), 
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"number_of_monsters_to_summon" = 1
		mod("MinionModifier", "LIST", { mod = mod("Damage", "INC", 140) }), --"minion_damage_+%" = 140
		mod("MinionModifier", "LIST", { mod = mod("Life", "INC", 150) }), --"minion_maximum_life_+%" = 150
		--"display_minion_monster_type" = 4
		skill("minionLevel", 75), --"display_minion_monster_level" = 75
		--"cast_when_hit_%" = 100
		mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", 400) }), --"active_skill_minion_damage_+%_final" = 400
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfSpiteWhenHit"] = {
	name = "怨恨之誓",
	hidden = true,
	color = 4,
	description = "制造一个你的武器的复制品或是投射物的新星, 并在其路径上留下冰缓地面. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [48] = true, [3] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 1.5), 
		skill("baseMultiplier", 1.5), 
		skill("cooldown", 5), 
		--"base_projectile_ground_effect_duration" = 2000
		mod("ProjectileCount", "BASE", 9), --"number_of_additional_projectiles" = 9
		--"melee_counterattack_trigger_on_hit_%" = 100
		--"skill_art_variation" = 2
		mod("SkillPhysicalDamageConvertToCold", "BASE", 50), --"skill_physical_damage_%_to_convert_to_cold" = 50
		--"projectiles_drop_ground_ice" = ?
		--"projectiles_drop_ground_effects_on_client" = ?
		--"base_is_projectile" = ?
		--"projectiles_nova" = ?
		--"skill_can_fire_arrows" = ?
		--"skill_can_fire_wand_projectiles" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfSpiteWhenHit2"] = {
	name = "怨恨之律",
	hidden = true,
	color = 4,
	description = "制造一个你的武器的复制品或是投射物的新星, 并在其路径上留下冰缓地面. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [48] = true, [3] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 2.1), 
		skill("baseMultiplier", 2.1), 
		skill("cooldown", 5), 
		--"base_projectile_ground_effect_duration" = 2000
		mod("ProjectileCount", "BASE", 9), --"number_of_additional_projectiles" = 9
		--"melee_counterattack_trigger_on_hit_%" = 100
		--"skill_art_variation" = 2
		mod("SkillPhysicalDamageConvertToCold", "BASE", 50), --"skill_physical_damage_%_to_convert_to_cold" = 50
		--"projectiles_drop_ground_ice" = ?
		--"projectiles_drop_ground_effects_on_client" = ?
		--"base_is_projectile" = ?
		--"projectiles_nova" = ?
		--"skill_can_fire_arrows" = ?
		--"skill_can_fire_wand_projectiles" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfSpiteWhenHit3"] = {
	name = "怨恨之令",
	hidden = true,
	color = 4,
	description = "制造一个你的武器的复制品或是投射物的新星, 并在其路径上留下冰缓地面. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [48] = true, [3] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 2.7), 
		skill("baseMultiplier", 2.7), 
		skill("cooldown", 5), 
		--"base_projectile_ground_effect_duration" = 2000
		mod("ProjectileCount", "BASE", 9), --"number_of_additional_projectiles" = 9
		--"melee_counterattack_trigger_on_hit_%" = 100
		--"skill_art_variation" = 2
		mod("SkillPhysicalDamageConvertToCold", "BASE", 50), --"skill_physical_damage_%_to_convert_to_cold" = 50
		--"projectiles_drop_ground_ice" = ?
		--"projectiles_drop_ground_effects_on_client" = ?
		--"base_is_projectile" = ?
		--"projectiles_nova" = ?
		--"skill_can_fire_arrows" = ?
		--"skill_can_fire_wand_projectiles" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfSpiteWhenHit4"] = {
	name = "怨恨之诫",
	hidden = true,
	color = 4,
	description = "制造一个你的武器的复制品或是投射物的新星, 并在其路径上留下冰缓地面. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [48] = true, [3] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 3.3), 
		skill("baseMultiplier", 3.3), 
		skill("cooldown", 5), 
		--"base_projectile_ground_effect_duration" = 2000
		mod("ProjectileCount", "BASE", 9), --"number_of_additional_projectiles" = 9
		--"melee_counterattack_trigger_on_hit_%" = 100
		--"skill_art_variation" = 2
		mod("SkillPhysicalDamageConvertToCold", "BASE", 50), --"skill_physical_damage_%_to_convert_to_cold" = 50
		--"projectiles_drop_ground_ice" = ?
		--"projectiles_drop_ground_effects_on_client" = ?
		--"base_is_projectile" = ?
		--"projectiles_nova" = ?
		--"skill_can_fire_arrows" = ?
		--"skill_can_fire_wand_projectiles" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfTempestOnHit"] = {
	name = "风暴之誓",
	hidden = true,
	color = 4,
	description = "在短暂聚能之后释放, 对你周围的敌人造成伤害. 有短暂的冷却时间. ",
	skillTypes = { [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 4), 
		skill("CritChance", 7), 
		skill("cooldown", 10), 
		skill("LightningMin", 175), --"spell_minimum_base_lightning_damage" = 175
		skill("LightningMax", 280), --"spell_maximum_base_lightning_damage" = 280
		mod("AreaOfEffect", "INC", 0), --"base_skill_area_of_effect_+%" = 0
		--"skill_art_variation" = 0
		--"cast_on_hit_%" = 100
		skill("duration", 2), --"base_skill_effect_duration" = 2000
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfTempestOnHit2"] = {
	name = "风暴之律",
	hidden = true,
	color = 4,
	description = "在短暂聚能之后释放, 对你周围的敌人造成伤害. 有短暂的冷却时间. ",
	skillTypes = { [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 4), 
		skill("CritChance", 7), 
		skill("cooldown", 10), 
		skill("LightningMin", 812), --"spell_minimum_base_lightning_damage" = 812
		skill("LightningMax", 1245), --"spell_maximum_base_lightning_damage" = 1245
		mod("AreaOfEffect", "INC", 0), --"base_skill_area_of_effect_+%" = 0
		--"skill_art_variation" = 0
		--"cast_on_hit_%" = 100
		skill("duration", 2), --"base_skill_effect_duration" = 2000
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfTempestOnHit3"] = {
	name = "风暴之令",
	hidden = true,
	color = 4,
	description = "在短暂聚能之后释放, 对你周围的敌人造成伤害. 有短暂的冷却时间. ",
	skillTypes = { [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 4), 
		skill("CritChance", 7), 
		skill("cooldown", 10), 
		skill("LightningMin", 2044), --"spell_minimum_base_lightning_damage" = 2044
		skill("LightningMax", 3065), --"spell_maximum_base_lightning_damage" = 3065
		mod("AreaOfEffect", "INC", 0), --"base_skill_area_of_effect_+%" = 0
		--"skill_art_variation" = 0
		--"cast_on_hit_%" = 100
		skill("duration", 2), --"base_skill_effect_duration" = 2000
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfTempestOnHit4"] = {
	name = "风暴之诫",
	hidden = true,
	color = 4,
	description = "在短暂聚能之后释放, 对你周围的敌人造成伤害. 有短暂的冷却时间. ",
	skillTypes = { [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 4), 
		skill("CritChance", 7), 
		skill("cooldown", 10), 
		skill("LightningMin", 3739), --"spell_minimum_base_lightning_damage" = 3739
		skill("LightningMax", 5920), --"spell_maximum_base_lightning_damage" = 5920
		mod("AreaOfEffect", "INC", 0), --"base_skill_area_of_effect_+%" = 0
		--"skill_art_variation" = 0
		--"cast_on_hit_%" = 100
		skill("duration", 2), --"base_skill_effect_duration" = 2000
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfTheGraveOnKill"] = {
	name = "冰墓之誓",
	hidden = true,
	color = 4,
	description = "召唤一个寒冰的颅骨, 在持续时间结束时爆炸. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [9] = true, [21] = true, [34] = true, [36] = true, [42] = true, [12] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [28] = true, },
	minionList = {
		"IcyRagingSpirit",
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 5), 
		--"chance_to_cast_on_owned_kill_%" = 100
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"number_of_monsters_to_summon" = 3
		--"display_minion_monster_type" = 10
		skill("minionLevel", 32), --"display_minion_monster_level" = 32
		--"minions_explode_on_death_for_%_max_life_at_end_of_duration" = 20
		--"minions_cannot_taunt_enemies" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfTheGraveOnKill2"] = {
	name = "冰墓之律",
	hidden = true,
	color = 4,
	description = "召唤一个寒冰的颅骨, 在持续时间结束时爆炸. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [9] = true, [21] = true, [34] = true, [36] = true, [42] = true, [12] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [28] = true, },
	minionList = {
		"IcyRagingSpirit",
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 5), 
		--"chance_to_cast_on_owned_kill_%" = 100
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"number_of_monsters_to_summon" = 3
		--"display_minion_monster_type" = 10
		skill("minionLevel", 53), --"display_minion_monster_level" = 53
		--"minions_explode_on_death_for_%_max_life_at_end_of_duration" = 20
		--"minions_cannot_taunt_enemies" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfTheGraveOnKill3"] = {
	name = "冰墓之令",
	hidden = true,
	color = 4,
	description = "召唤一个寒冰的颅骨, 在持续时间结束时爆炸. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [9] = true, [21] = true, [34] = true, [36] = true, [42] = true, [12] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [28] = true, },
	minionList = {
		"IcyRagingSpirit",
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 5), 
		--"chance_to_cast_on_owned_kill_%" = 100
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"number_of_monsters_to_summon" = 3
		--"display_minion_monster_type" = 10
		skill("minionLevel", 66), --"display_minion_monster_level" = 66
		--"minions_explode_on_death_for_%_max_life_at_end_of_duration" = 20
		--"minions_cannot_taunt_enemies" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfTheGraveOnKill4"] = {
	name = "冰墓之诫",
	hidden = true,
	color = 4,
	description = "召唤一个寒冰的颅骨, 在持续时间结束时爆炸. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [9] = true, [21] = true, [34] = true, [36] = true, [42] = true, [12] = true, },
	minionSkillTypes = { [1] = true, [24] = true, [25] = true, [28] = true, },
	minionList = {
		"IcyRagingSpirit",
	},
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 5), 
		--"chance_to_cast_on_owned_kill_%" = 100
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"number_of_monsters_to_summon" = 3
		--"display_minion_monster_type" = 10
		skill("minionLevel", 75), --"display_minion_monster_level" = 75
		--"minions_explode_on_death_for_%_max_life_at_end_of_duration" = 20
		--"minions_cannot_taunt_enemies" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfThunderOnKill"] = {
	name = "雷电之誓",
	hidden = true,
	color = 4,
	description = "在你的四周造成锥形的闪电伤害. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [31] = true, [35] = true, [42] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 7), 
		skill("cooldown", 5), 
		skill("LightningMin", 71), --"spell_minimum_base_lightning_damage" = 71
		skill("LightningMax", 114), --"spell_maximum_base_lightning_damage" = 114
		--"chance_to_cast_on_kill_%_target_self" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfThunderOnKill2"] = {
	name = "雷电之律",
	hidden = true,
	color = 4,
	description = "在你的四周造成锥形的闪电伤害. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [31] = true, [35] = true, [42] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 7), 
		skill("cooldown", 5), 
		skill("LightningMin", 330), --"spell_minimum_base_lightning_damage" = 330
		skill("LightningMax", 506), --"spell_maximum_base_lightning_damage" = 506
		--"chance_to_cast_on_kill_%_target_self" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfThunderOnKill3"] = {
	name = "雷电之令",
	hidden = true,
	color = 4,
	description = "在你的四周造成锥形的闪电伤害. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [31] = true, [35] = true, [42] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 7), 
		skill("cooldown", 5), 
		skill("LightningMin", 830), --"spell_minimum_base_lightning_damage" = 830
		skill("LightningMax", 1245), --"spell_maximum_base_lightning_damage" = 1245
		--"chance_to_cast_on_kill_%_target_self" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfThunderOnKill4"] = {
	name = "雷电之诫",
	hidden = true,
	color = 4,
	description = "在你的四周造成锥形的闪电伤害. 此技能有短暂冷却时间. ",
	skillTypes = { [2] = true, [11] = true, [31] = true, [35] = true, [42] = true, [36] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		hit = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 7), 
		skill("cooldown", 5), 
		skill("LightningMin", 1519), --"spell_minimum_base_lightning_damage" = 1519
		skill("LightningMax", 2405), --"spell_maximum_base_lightning_damage" = 2405
		--"chance_to_cast_on_kill_%_target_self" = 100
		--"is_area_damage" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfWarOnKill"] = {
	name = "战争之誓",
	hidden = true,
	color = 4,
	description = "召唤一个你所使用的武器的复制体来攻击敌人. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [7] = true, [25] = true, [28] = true, [24] = true, [12] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 5), 
		skill("duration", 10), --"base_skill_effect_duration" = 10000
		--"number_of_monsters_to_summon" = 1
		--"attack_trigger_on_kill_%" = 100
		mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", 50) }), --"active_skill_minion_damage_+%_final" = 50
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfWarOnKill2"] = {
	name = "战争之律",
	hidden = true,
	color = 4,
	description = "召唤一个你所使用的武器的复制体来攻击敌人. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [7] = true, [25] = true, [28] = true, [24] = true, [12] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 5), 
		skill("duration", 10), --"base_skill_effect_duration" = 10000
		--"number_of_monsters_to_summon" = 1
		--"attack_trigger_on_kill_%" = 100
		mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", 100) }), --"active_skill_minion_damage_+%_final" = 100
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfWarOnKill3"] = {
	name = "战争之令",
	hidden = true,
	color = 4,
	description = "召唤一个你所使用的武器的复制体来攻击敌人. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [7] = true, [25] = true, [28] = true, [24] = true, [12] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 5), 
		skill("duration", 10), --"base_skill_effect_duration" = 10000
		--"number_of_monsters_to_summon" = 1
		--"attack_trigger_on_kill_%" = 100
		mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", 150) }), --"active_skill_minion_damage_+%_final" = 150
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfWarOnKill4"] = {
	name = "战争之诫",
	hidden = true,
	color = 4,
	description = "召唤一个你所使用的武器的复制体来攻击敌人. 此技能有短暂冷却时间. ",
	skillTypes = { [1] = true, [7] = true, [25] = true, [28] = true, [24] = true, [12] = true, [47] = true, [57] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Wand"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Bow"] = true,
		["One Handed Mace"] = true,
	},
	fromItem = true,
	baseFlags = {
		attack = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 5), 
		skill("duration", 10), --"base_skill_effect_duration" = 10000
		--"number_of_monsters_to_summon" = 1
		--"attack_trigger_on_kill_%" = 100
		mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", 200) }), --"active_skill_minion_damage_+%_final" = 200
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}
skills["EnchantmentOfWinterWhenHit"] = {
	name = "冬之誓",
	hidden = true,
	color = 4,
	description = "释放出带有冰霜脉冲的冰冻投射物. 有短暂的冷却时间.",
	skillTypes = { [3] = true, [68] = true, [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [26] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1.4), 
		skill("CritChance", 5), 
		skill("cooldown", 10), 
		skill("ColdMin", 48), --"spell_minimum_base_cold_damage" = 48
		skill("ColdMax", 76), --"spell_maximum_base_cold_damage" = 76
		--"skill_art_variation" = 1
		--"cast_when_hit_%" = 100
		--"is_area_damage" = ?
		--"base_is_projectile" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 32, },
	},
}
skills["EnchantmentOfWinterWhenHit2"] = {
	name = "冬之律",
	hidden = true,
	color = 4,
	description = "释放出带有冰霜脉冲的冰冻投射物. 有短暂的冷却时间.",
	skillTypes = { [3] = true, [68] = true, [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [26] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1.4), 
		skill("CritChance", 5), 
		skill("cooldown", 10), 
		skill("ColdMin", 221), --"spell_minimum_base_cold_damage" = 221
		skill("ColdMax", 340), --"spell_maximum_base_cold_damage" = 340
		--"skill_art_variation" = 1
		--"cast_when_hit_%" = 100
		--"is_area_damage" = ?
		--"base_is_projectile" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 53, },
	},
}
skills["EnchantmentOfWinterWhenHit3"] = {
	name = "冬之令",
	hidden = true,
	color = 4,
	description = "释放出带有冰霜脉冲的冰冻投射物. 有短暂的冷却时间.",
	skillTypes = { [3] = true, [68] = true, [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [26] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1.4), 
		skill("CritChance", 5), 
		skill("cooldown", 10), 
		skill("ColdMin", 557), --"spell_minimum_base_cold_damage" = 557
		skill("ColdMax", 836), --"spell_maximum_base_cold_damage" = 836
		--"skill_art_variation" = 1
		--"cast_when_hit_%" = 100
		--"is_area_damage" = ?
		--"base_is_projectile" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 66, },
	},
}
skills["EnchantmentOfWinterWhenHit4"] = {
	name = "冬之诫",
	hidden = true,
	color = 4,
	description = "释放出带有冰霜脉冲的冰冻投射物. 有短暂的冷却时间.",
	skillTypes = { [3] = true, [68] = true, [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [26] = true, [36] = true, [42] = true, },
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1.4), 
		skill("CritChance", 5), 
		skill("cooldown", 10), 
		skill("ColdMin", 1020), --"spell_minimum_base_cold_damage" = 1020
		skill("ColdMax", 1615), --"spell_maximum_base_cold_damage" = 1615
		--"skill_art_variation" = 1
		--"cast_when_hit_%" = 100
		--"is_area_damage" = ?
		--"base_is_projectile" = ?
		--"damage_cannot_be_reflected" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 75, },
	},
}