-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Minion active skills
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...

skills["ChaosElementalCascadeSummoned"] = {
	name = "冰霜之刺",
	hidden = true,
	color = 3,
	description = "从地面上不断的冒出冰结之刺, 宛如川流一般向前攻击并对敌人造成伤害.",
	skillTypes = { [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [26] = true, [36] = true, [34] = true, [60] = true, },
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 0.8), 
		skill("damageEffectiveness", 0.6), 
		skill("cooldown", 3.5), 
		skill("PhysicalMin", 9), --"spell_minimum_base_physical_damage" = 9
		skill("PhysicalMax", 13), --"spell_maximum_base_physical_damage" = 13
		--"upheaval_number_of_spikes" = 6
		mod("Speed", "INC", 0, ModFlag.Cast), --"base_cast_speed_+%" = 0
		--"skill_art_variation" = 3
		mod("SkillPhysicalDamageConvertToChaos", "BASE", 50), --"skill_physical_damage_%_to_convert_to_chaos" = 50
		--"monster_penalty_against_minions_damage_+%_final_vs_player_minions" = -25
		--"is_area_damage" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 4, },
	},
}
skills["SandstormChaosElementalSummoned"] = {
	name = "混沌光环",
	hidden = true,
	color = 4,
	skillTypes = { [2] = true, [11] = true, [12] = true, },
	baseFlags = {
		spell = true,
		duration = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 8), 
		skill("ChaosDot", 14.533333333333), --"base_chaos_damage_to_deal_per_minute" = 872
		skill("duration", 5), --"base_skill_effect_duration" = 5000
		--"active_skill_area_of_effect_radius_+%_final" = 0
		--"skill_art_variation" = 2
		--"is_area_damage" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 3, },
	},
}
skills["FireElementalFlameRedSummoned"] = {
	name = "献祭",
	hidden = true,
	color = 4,
	description = "召唤一个图腾, 它会持续的对附近的敌人喷射火焰.",
	skillTypes = { [2] = true, [3] = true, [68] = true, [10] = true, [17] = true, [19] = true, [30] = true, [33] = true, },
	skillTotemId = 8,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 0.25), 
		skill("damageEffectiveness", 0.2), 
		skill("FireMin", 6), --"spell_minimum_base_fire_damage" = 6
		skill("FireMax", 8), --"spell_maximum_base_fire_damage" = 8
		--"skill_art_variation" = 4
		mod("Speed", "MORE", -89, ModFlag.Cast), --"active_skill_cast_speed_+%_final" = -89
		--"spell_maximum_action_distance_+%" = -77
		--"monster_penalty_against_minions_damage_+%_final_vs_player_minions" = -25
		--"base_is_projectile" = ?
		flag("PierceAllTargets"), --"always_pierce" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 3, },
	},
}
skills["FireElementalMortarSummoned"] = {
	name = "熔岩球",
	hidden = true,
	color = 4,
	description = "通用的怪物炮击技能. 与怪物投射物相似, 但带有冲击效果.",
	skillTypes = { [3] = true, [68] = true, [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [26] = true, [36] = true, },
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("cooldown", 6), 
		--"monster_projectile_variation" = 3
		--"projectile_spread_radius" = 15
		skill("FireMin", 152), --"spell_minimum_base_fire_damage" = 152
		skill("FireMax", 228), --"spell_maximum_base_fire_damage" = 228
		--"spell_maximum_action_distance_+%" = -33
		--"is_area_damage" = ?
		--"base_is_projectile" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 34, },
	},
}
skills["FireElementalConeSummoned"] = {
	name = "火焰震波",
	hidden = true,
	color = 3,
	skillTypes = { [2] = true, [10] = true, [11] = true, [17] = true, [18] = true, [19] = true, [26] = true, [36] = true, [33] = true, },
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 0.935), 
		skill("CritChance", 10), 
		skill("cooldown", 2), 
		--"is_area_damage" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
		[2] = skill("FireMin", nil), --"spell_minimum_base_fire_damage"
		[3] = skill("FireMax", nil), --"spell_maximum_base_fire_damage"
	},
	levels = {
		[1] = { 34, 106, 165, },
		[2] = { 36, 117, 184, },
		[3] = { 38, 131, 204, },
		[4] = { 40, 145, 226, },
		[5] = { 42, 160, 250, },
		[6] = { 44, 177, 277, },
		[7] = { 46, 196, 306, },
		[8] = { 48, 216, 337, },
		[9] = { 50, 237, 371, },
		[10] = { 52, 261, 408, },
		[11] = { 54, 287, 448, },
		[12] = { 56, 315, 492, },
		[13] = { 58, 346, 540, },
		[14] = { 60, 379, 592, },
		[15] = { 62, 415, 648, },
		[16] = { 64, 454, 709, },
		[17] = { 66, 496, 775, },
		[18] = { 68, 542, 847, },
		[19] = { 69, 566, 885, },
		[20] = { 70, 592, 924, },
		[21] = { 72, 645, 1008, },
		[22] = { 74, 704, 1100, },
		[23] = { 76, 767, 1198, },
		[24] = { 78, 835, 1305, },
		[25] = { 80, 910, 1421, },
		[26] = { 82, 990, 1546, },
		[27] = { 84, 1076, 1682, },
		[28] = { 86, 1170, 1828, },
		[29] = { 88, 1271, 1987, },
		[30] = { 90, 1381, 2158, },
	},
}
skills["IceElementalIceCyclone"] = {
	name = "旋风斩",
	hidden = true,
	color = 2,
	description = "对周围敌人造成伤害, 接而进行一连串的旋转攻击, 边向目标地点前进边攻击路径上的敌人, 无法被多重打击和无情辅助.",
	skillTypes = { [1] = true, [11] = true, [24] = true, [38] = true, [65] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Staff"] = true,
		["None"] = true,
		["Sceptre"] = true,
		["Two Handed Axe"] = true,
		["Dagger"] = true,
		["Two Handed Sword"] = true,
		["Claw"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Mace"] = true,
	},
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
		movement = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 6), 
		--"skill_art_variation" = 4
		mod("MovementSpeed", "MORE", 75), --"cyclone_movement_speed_+%_final" = 75
		--"cyclone_extra_distance" = 40
		mod("Damage", "MORE", -20), --"active_skill_damage_+%_final" = -20
		skill("duration", 4), --"base_skill_effect_duration" = 4000
		--"is_area_damage" = ?
		--"cyclone_places_ground_ice" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}
skills["IceElementalSpearSummoned"] = {
	name = "冰矛",
	hidden = true,
	color = 3,
	skillTypes = { [3] = true, [68] = true, [2] = true, [17] = true, [18] = true, },
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 4), 
		skill("ColdMin", 10), --"spell_minimum_base_cold_damage" = 10
		skill("ColdMax", 15), --"spell_maximum_base_cold_damage" = 15
		--"monster_reverse_point_blank_damage_-%_at_minimum_range" = 25
		--"base_is_projectile" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 3, },
	},
}
skills["LightningGolemArcSummoned"] = {
	name = "风暴漩涡",
	hidden = true,
	color = 3,
	skillTypes = { [12] = true, [35] = true, [3] = true, [68] = true, [14] = true, [2] = true, },
	baseFlags = {
		spell = true,
		projectile = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 0.8), 
		skill("damageEffectiveness", 0.6), 
		skill("CritChance", 5), 
		skill("cooldown", 8), 
		skill("LightningMin", 1), --"spell_minimum_base_lightning_damage" = 1
		skill("LightningMax", 8), --"spell_maximum_base_lightning_damage" = 8
		skill("duration", 8), --"base_skill_effect_duration" = 8000
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}
skills["MonsterProjectileSpellLightningGolemSummoned"] = {
	name = "闪电投射物",
	hidden = true,
	color = 4,
	skillTypes = { [2] = true, [3] = true, [68] = true, [36] = true, },
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("CritChance", 5), 
		skill("LightningMin", 2), --"spell_minimum_base_lightning_damage" = 2
		skill("LightningMax", 18), --"spell_maximum_base_lightning_damage" = 18
		--"monster_projectile_variation" = 11
		mod("Speed", "MORE", -15, ModFlag.Cast), --"active_skill_cast_speed_+%_final" = -15
		--"spell_maximum_action_distance_+%" = -40
		--"base_is_projectile" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}
skills["LightningGolemWrath"] = {
	name = "雷霆",
	hidden = true,
	color = 3,
	skillTypes = { [2] = true, [11] = true, [5] = true, [16] = true, [44] = true, [35] = true, [12] = true, },
	baseFlags = {
		spell = true,
		aura = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("castTime", 0.8), 
		skill("cooldown", 12), 
		mod("LightningMin", "BASE", 1, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }), --"attack_minimum_added_lightning_damage" = 1
		mod("LightningMax", "BASE", 1, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }), --"attack_maximum_added_lightning_damage" = 1
		skill("duration", 4), --"base_skill_effect_duration" = 4000
		mod("LightningMin", "BASE", 1, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }), --"spell_minimum_added_lightning_damage" = 1
		mod("LightningMax", "BASE", 1, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }), --"spell_maximum_added_lightning_damage" = 1
		--"base_deal_no_damage" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}
skills["SpectralSkullShieldCharge"] = {
	name = "重盾冲锋",
	hidden = true,
	color = 4,
	description = "向一个目标冲锋, 使用盾牌对其猛击的同时也用近战武器顺手补刀. 此攻击将会击退目标并将其击晕, 在路径上的敌人将会被推向两旁. 伤害与击晕几率将视冲锋距离而定. ",
	skillTypes = { [1] = true, [7] = true, [13] = true, [24] = true, [25] = true, [38] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Sceptre"] = true,
		["None"] = true,
		["Dagger"] = true,
		["Claw"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["One Handed Mace"] = true,
	},
	baseFlags = {
		attack = true,
		melee = true,
		movement = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 5), 
		--"shield_charge_stun_duration_+%_maximum" = 200
		mod("MovementSpeed", "INC", 500, 0, 0, nil), --"base_movement_velocity_+%" = 500
		--"shield_charge_damage_+%_maximum" = 300
		mod("Damage", "MORE", -50), --"active_skill_damage_+%_final" = -50
		--"ignores_proximity_shield" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}
skills["SkeletonProjectileCold"] = {
	name = "冰霜投射物",
	hidden = true,
	color = 4,
	skillTypes = { [2] = true, [10] = true, [26] = true, [3] = true, [68] = true, },
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1.95), 
		skill("CritChance", 5), 
		--"base_is_projectile" = 1
		--"spell_maximum_action_distance_+%" = -60
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
		[2] = skill("manaCost", nil), 
		[3] = skill("ColdMin", nil), --"spell_minimum_base_cold_damage"
		[4] = skill("ColdMax", nil), --"spell_maximum_base_cold_damage"
	},
	levels = {
		[1] = { 4, 5, 3, 5, },
		[2] = { 19, 4, 11, 17, },
		[3] = { 68, 4, 687, 1071, },
	},
}
skills["SkeletonProjectileFire"] = {
	name = "火焰投射物",
	hidden = true,
	color = 4,
	skillTypes = { [2] = true, [10] = true, [26] = true, [3] = true, [68] = true, },
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1.95), 
		skill("CritChance", 5), 
		--"base_is_projectile" = 1
		--"spell_maximum_action_distance_+%" = -60
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
		[2] = skill("manaCost", nil), 
		[3] = skill("FireMin", nil), --"spell_minimum_base_fire_damage"
		[4] = skill("FireMax", nil), --"spell_maximum_base_fire_damage"
	},
	levels = {
		[1] = { 4, 5, 4, 6, },
		[2] = { 19, 4, 14, 21, },
		[3] = { 68, 4, 840, 1309, },
	},
}
skills["SkeletonProjectileLightning"] = {
	name = "闪电投射物",
	hidden = true,
	color = 4,
	skillTypes = { [2] = true, [10] = true, [26] = true, [3] = true, [68] = true, },
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1.95), 
		skill("CritChance", 5), 
		--"base_is_projectile" = 1
		--"spell_maximum_action_distance_+%" = -60
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
		[2] = skill("manaCost", nil), 
		[3] = skill("LightningMin", nil), --"spell_minimum_base_lightning_damage"
		[4] = skill("LightningMax", nil), --"spell_maximum_base_lightning_damage"
	},
	levels = {
		[1] = { 4, 5, 3, 8, },
		[2] = { 19, 4, 10, 29, },
		[3] = { 68, 4, 409, 1221, },
	},
}
skills["RockGolemSlam"] = {
	name = "横扫",
	hidden = true,
	color = 1,
	skillTypes = { [1] = true, [11] = true, [57] = true, [36] = true, },
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("damageEffectiveness", 1.75), 
		skill("baseMultiplier", 1.75), 
		skill("cooldown", 6), 
		mod("Speed", "MORE", -20, ModFlag.Attack), --"active_skill_attack_speed_+%_final" = -20
		--"chance_to_taunt_on_hit_%" = 33
		--"skill_art_variation" = 1
		--"active_skill_area_of_effect_radius_+%_final" = 0
		--"is_area_damage" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}
skills["RockGolemWhirlingBlades"] = {
	name = "回旋之刃",
	hidden = true,
	color = 4,
	description = "迅速穿越敌人并同时造成武器伤害. 限定匕首, 爪以及单手剑. ",
	skillTypes = { [1] = true, [24] = true, [38] = true, },
	weaponTypes = {
		["One Handed Sword"] = true,
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Dagger"] = true,
	},
	baseFlags = {
		attack = true,
		melee = true,
		movement = true,
	},
	baseMods = {
		skill("castTime", 2.6), 
		--"skill_sound_variation" = 1
		mod("Speed", "MORE", -50, ModFlag.Attack), --"active_skill_attack_speed_+%_final" = -50
		--"monster_flurry" = 1
		skill("castTimeOverridesAttackTime", true), --"cast_time_overrides_attack_duration" = ?
		--"ignores_proximity_shield" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}
skills["ZombieSlam"] = {
	name = "横扫",
	hidden = true,
	color = 4,
	skillTypes = { [1] = true, [11] = true, [57] = true, [36] = true, },
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
		skill("castTime", 1), 
		skill("cooldown", 5), 
		mod("Speed", "MORE", -22, ModFlag.Attack), --"active_skill_attack_speed_+%_final" = -22
		mod("Damage", "MORE", 45), --"active_skill_damage_+%_final" = 45
		skill("duration", 0.28), --"base_skill_effect_duration" = 280
		--"is_area_damage" = ?
		skill("cannotBeEvaded", true), --"global_always_hit" = ?
		skill("radius", 18), 
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}
skills["SpiderMinionLeapSlam"] = {
	name = "跃击",
	hidden = true,
	color = 4,
	description = "朝着目标区域跃起, 并在落地时以主手武器重击（并击退一些）范围内的敌人. 被踩到的敌人将会被推出去. 限定一把斧, 锤, 剑或是长杖.",
	skillTypes = { [1] = true, [7] = true, [11] = true, [24] = true, [38] = true, },
	weaponTypes = {
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["Thrusting One Handed Sword"] = true,
		["Staff"] = true,
		["Two Handed Sword"] = true,
		["One Handed Sword"] = true,
		["Sceptre"] = true,
		["One Handed Axe"] = true,
		["One Handed Mace"] = true,
	},
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
		movement = true,
	},
	baseMods = {
		skill("castTime", 1.4), 
		skill("damageEffectiveness", 1.5), 
		skill("baseMultiplier", 1.5), 
		skill("cooldown", 2), 
		--"skill_art_variation" = 3
		--"active_skill_area_of_effect_radius_+%_final" = 0
		--"is_area_damage" = ?
		skill("castTimeOverridesAttackTime", true), --"cast_time_overrides_attack_duration" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}
skills["SummonPhantasmFadingProjectile"] = {
	name = "物理投射物",
	hidden = true,
	color = 4,
	skillTypes = { [2] = true, [3] = true, [10] = true, },
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("castTime", 1.17), 
		skill("CritChance", 5), 
		skill("PhysicalMin", 3), --"spell_minimum_base_physical_damage" = 3
		skill("PhysicalMax", 5), --"spell_maximum_base_physical_damage" = 5
		--"base_is_projectile" = ?
		flag("PierceAllTargets"), --"always_pierce" = ?
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}
skills["MinionInstability"] = {
	name = "复仇之灵",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		fire = true,
	},
	skillTypes = { [10] = true, },
	baseMods = {
		skill("FireMin", 1, { type = "PerStat", stat = "Life", div = 1/.33 }),
		skill("FireMax", 1, { type = "PerStat", stat = "Life", div = 1/.33 }),
		skill("showAverage", true),
		skill("radius", 22),
	},
	qualityMods = {
	},
	levelMods = {
	},
	levels = {
		[1] = { },
	},
}
skills["BeaconCausticCloud"] = {
	name = "腐蚀的毒云",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		chaos = true,
	},
	skillTypes = { },
	baseMods = {
		skill("ChaosDot", 1, { type = "PerStat", stat = "Life", div = 10 }),
		skill("dotIsArea", true),
	},
	qualityMods = {
	},
	levelMods = {
	},
	levels = {
		[1] = { },
	},
}
skills["BeaconZombieCausticCloud"] = {
	name = "腐蚀的毒云",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		chaos = true,
	},
	skillTypes = { },
	baseMods = {
		skill("ChaosDot", 1, { type = "PerStat", stat = "Life", div = 2 }),
		skill("dotIsArea", true),
	},
	qualityMods = {
	},
	levelMods = {
	},
	levels = {
		[1] = { },
	},
}


skills["DancingDervishCyclone"] = {
	name = "旋风斩",
	hidden = true,
	color = 2,
	description = "对你周围的敌人造成伤害，然后跟着旋转着移动到你的位置，对路径上的敌人进行一系列攻击",
	skillTypes = { [1] = true, [6] = true, [11] = true, [24] = true, [38] = true, },
	weaponTypes = {
		["None"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
	},
	baseMods = {
		skill("castTime", 1), 
		mod("PhysicalDamage", "INC", 0), --"physical_damage_+%" = 0
		mod("Speed", "INC", 20, ModFlag.Attack, 0, nil), --"attack_speed_+%" = 20
		--"skill_art_variation" = 0
		mod("MovementSpeed", "MORE", 0), --"cyclone_movement_speed_+%_final" = 0
		--"cyclone_extra_distance" = 25
		mod("Damage", "MORE", 0, ModFlag.Hit), --"active_skill_damage_+%_final" = 0
		--"is_area_damage" = ?
		skill("dpsMultiplier", 2), 
		skill("radiusIsWeaponRange", true), 
	},
	qualityMods = {
	},
	levelMods = {
		[1] = skill("levelRequirement", nil), 
	},
	levels = {
		[1] = { 1, },
	},
}