-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Minion active skills
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...



skills["ChaosElementalCascadeSummoned"] = {
name = "冰川之刺",
	hidden = true,
	color = 3,
	baseEffectiveness = 1.9800000190735,
	incrementalEffectiveness = 0.037999998778105,
	description = "从地面上不断的冒出冰结之刺, 宛如川流一般向前攻击并对敌人造成伤害.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Triggerable] = true, [SkillType.ColdSkill] = true, [SkillType.PhysicalSkill] = true, [SkillType.CanRapidFire] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"upheaval_number_of_spikes",
		"base_cast_speed_+%",
		"skill_art_variation",
		"skill_physical_damage_%_to_convert_to_chaos",
		"monster_penalty_against_minions_damage_+%_final_vs_player_minions",
		"is_area_damage",
	},
	statInterpolation = { 3, 3, 1, 1, 1, 1, 1, },
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, 6, 0, 3, 50, -25, damageEffectiveness = 0.6, cooldown = 3.5, levelRequirement = 4, },
	},
}
skills["SandstormChaosElementalSummoned"] = {
name = "混沌光环",
	hidden = true,
	color = 4,
	baseEffectiveness = 11,
	incrementalEffectiveness = 0.016499999910593,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Area] = true, [SkillType.Duration] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		duration = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_chaos_damage_to_deal_per_minute",
		"base_skill_effect_duration",
		"active_skill_area_of_effect_radius_+%_final",
		"skill_art_variation",
		"is_area_damage",
	},
	statInterpolation = { 3, 1, 1, 1, },
	levels = {
		[1] = { 16.666667039196, 5000, 0, 2, cooldown = 8, levelRequirement = 3, },
	},
}
skills["FireElementalFlameRedSummoned"] = {
name = "献祭",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.3999999761581,
	incrementalEffectiveness = 0.041999999433756,
	description = "召唤一个图腾, 它会持续的对附近的敌人喷射火焰.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Hit] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanMine] = true, [SkillType.Totem] = true, [SkillType.FireSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	skillTotemId = 8,
	castTime = 0.25,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"skill_art_variation",
		"active_skill_cast_speed_+%_final",
		"spell_maximum_action_distance_+%",
		"monster_penalty_against_minions_damage_+%_final_vs_player_minions",
		"base_is_projectile",
		"always_pierce",
	},
	statInterpolation = { 3, 3, 1, 1, 1, 1, },
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, 4, -89, -77, -25, damageEffectiveness = 0.2, levelRequirement = 3, },
	},
}
skills["FireElementalMortarSummoned"] = {
name = "岩浆球",
	hidden = true,
	color = 4,
	baseEffectiveness = 4.2666997909546,
	incrementalEffectiveness = 0.032000001519918,
	description = "通用的怪物炮击技能. 与怪物投射物相似, 但带有冲击效果.",
	skillTypes = { [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Triggerable] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		projectile = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"projectile_spread_radius",
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"spell_maximum_action_distance_+%",
		"is_area_damage",
		"base_is_projectile",
	},
	statInterpolation = { 1, 3, 3, 1, },
	levels = {
		[1] = { 15, 0.80000001192093, 1.2000000476837, -33, critChance = 5, cooldown = 6, levelRequirement = 34, },
	},
}
skills["FireElementalConeSummoned"] = {
name = "火焰震波",
	hidden = true,
	color = 3,
	baseEffectiveness = 2.9867000579834,
	incrementalEffectiveness = 0.031700000166893,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Triggerable] = true, [SkillType.FireSkill] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.935,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"is_area_damage",
	},
	statInterpolation = { 3, 3, },
	levels = {
		[1] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 34, },
		[2] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 36, },
		[3] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 38, },
		[4] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 40, },
		[5] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 42, },
		[6] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 44, },
		[7] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 46, },
		[8] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 48, },
		[9] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 50, },
		[10] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 52, },
		[11] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 54, },
		[12] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 56, },
		[13] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 58, },
		[14] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 60, },
		[15] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 62, },
		[16] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 64, },
		[17] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 66, },
		[18] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 68, },
		[19] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 69, },
		[20] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 70, },
		[21] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 72, },
		[22] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 74, },
		[23] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 76, },
		[24] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 78, },
		[25] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 80, },
		[26] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 82, },
		[27] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 84, },
		[28] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 86, },
		[29] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 88, },
		[30] = { 0.80000001192093, 1.25, critChance = 10, cooldown = 2, levelRequirement = 90, },
	},
}
skills["IceElementalIceCyclone"] = {
name = "旋风斩",
	hidden = true,
	color = 2,
	description = "对周围敌人造成伤害, 接而进行一连串的旋转攻击, 边向目标地点前进边攻击路径上的敌人, 无法被多重打击和无情辅助.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Melee] = true, [SkillType.MovementSkill] = true, [SkillType.Type65] = true, },
	weaponTypes = {
		["None"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
		movement = true,
	},
	baseMods = {
		skill("dpsMultiplier", 2),
	},
	qualityStats = {
	},
	stats = {
		"skill_art_variation",
		"cyclone_movement_speed_+%_final",
		"cyclone_extra_distance",
		"active_skill_damage_+%_final",
		"base_skill_effect_duration",
		"is_area_damage",
		"cyclone_places_ground_ice",
	},
	statInterpolation = { 1, 1, 1, 1, 1, },
	levels = {
		[1] = { 4, 75, 40, -20, 4000, cooldown = 6, levelRequirement = 1, },
	},
}
skills["IceElementalSpearSummoned"] = {
name = "冰矛",
	hidden = true,
	color = 3,
	baseEffectiveness = 2.5455000400543,
	incrementalEffectiveness = 0.032000001519918,
	skillTypes = { [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Spell] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"monster_reverse_point_blank_damage_-%_at_minimum_range",
		"base_is_projectile",
	},
	statInterpolation = { 3, 3, 1, },
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, 25, cooldown = 4, levelRequirement = 3, },
	},
}
skills["LightningGolemArcSummoned"] = {
name = "风暴之珠",
	hidden = true,
	color = 3,
	baseEffectiveness = 1.0937999486923,
	incrementalEffectiveness = 0.026000000536442,
	skillTypes = { [SkillType.Duration] = true, [SkillType.LightningSkill] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.ProjectileDamage] = true, [SkillType.Spell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	baseFlags = {
		spell = true,
		projectile = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"base_skill_effect_duration",
	},
	statInterpolation = { 3, 3, 1, },
	levels = {
		[1] = { 0.20000000298023, 1.7999999523163, 8000, damageEffectiveness = 0.6, cooldown = 8, critChance = 5, levelRequirement = 1, },
	},
}
skills["MonsterProjectileSpellLightningGolemSummoned"] = {
name = "闪电投射物",
	hidden = true,
	color = 4,
	baseEffectiveness = 2.625,
	incrementalEffectiveness = 0.033500000834465,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"monster_projectile_variation",
		"active_skill_cast_speed_+%_final",
		"spell_maximum_action_distance_+%",
		"base_is_projectile",
	},
	statInterpolation = { 3, 3, 1, 1, 1, },
	levels = {
		[1] = { 0.20000000298023, 1.7999999523163, 11, -15, -40, critChance = 5, levelRequirement = 1, },
	},
}
skills["LightningGolemWrath"] = {
name = "雷霆",
	hidden = true,
	color = 3,
	baseEffectiveness = 0.16249999403954,
	incrementalEffectiveness = 0.019999999552965,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Area] = true, [SkillType.Buff] = true, [SkillType.ManaCostPercent] = true, [SkillType.Aura] = true, [SkillType.LightningSkill] = true, [SkillType.Duration] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	statMap = {
		["attack_minimum_added_lightning_damage"] = {
			mod("LightningMin", "BASE", nil, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["attack_maximum_added_lightning_damage"] = {
			mod("LightningMax", "BASE", nil, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["spell_minimum_added_lightning_damage"] = {
			mod("LightningMin", "BASE", nil, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["spell_maximum_added_lightning_damage"] = {
			mod("LightningMax", "BASE", nil, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }),
		},
	},
	baseFlags = {
		spell = true,
		aura = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"attack_minimum_added_lightning_damage",
		"attack_maximum_added_lightning_damage",
		"base_skill_effect_duration",
		"spell_minimum_added_lightning_damage",
		"spell_maximum_added_lightning_damage",
		"base_deal_no_damage",
	},
	statInterpolation = { 3, 3, 1, 3, 3, },
	levels = {
		[1] = { 0.20000000298023, 1.7999999523163, 4000, 0.11999999731779, 1.0800000429153, cooldown = 12, levelRequirement = 1, },
	},
}
skills["SpectralSkullShieldCharge"] = {
name = "重盾冲锋",
	hidden = true,
	color = 4,
	description = "向一个目标冲锋, 使用盾牌对其猛击的同时也用近战武器顺手补刀. 此攻击将会击退目标并将其击晕, 在路径上的敌人将会被推向两旁. 伤害与击晕几率将视冲锋距离而定. ",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.MovementSkill] = true, [SkillType.TravelSkill] = true, },
	weaponTypes = {
		["None"] = true,
		["Claw"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		movement = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"shield_charge_stun_duration_+%_maximum",
		"base_movement_velocity_+%",
		"shield_charge_damage_+%_maximum",
		"active_skill_damage_+%_final",
		"ignores_proximity_shield",
	},
	statInterpolation = { 1, 1, 1, 1, },
	levels = {
		[1] = { 200, 500, 300, -50, cooldown = 5, levelRequirement = 1, },
	},
}
skills["RagingSpiritMeleeAttack"] = {
	name = "普通攻击",
	hidden = true,
	color = 4,
	description = "对你的敌人无情痛击.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.ProjectileAttack] = true, [SkillType.SkillCanMirageArcher] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.AttackCanRepeat] = true, [SkillType.Melee] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"active_skill_damage_+%_final",
	},
	statInterpolation = { 1, },
	levels = {
		[1] = { 76, levelRequirement = 4, },
		[2] = { 71, levelRequirement = 6, },
		[3] = { 66, levelRequirement = 9, },
		[4] = { 61, levelRequirement = 12, },
		[5] = { 56, levelRequirement = 15, },
		[6] = { 52, levelRequirement = 19, },
		[7] = { 47, levelRequirement = 23, },
		[8] = { 42, levelRequirement = 28, },
		[9] = { 37, levelRequirement = 33, },
		[10] = { 32, levelRequirement = 39, },
		[11] = { 28, levelRequirement = 43, },
		[12] = { 23, levelRequirement = 46, },
		[13] = { 18, levelRequirement = 49, },
		[14] = { 12, levelRequirement = 52, },
		[15] = { 10, levelRequirement = 55, },
		[16] = { 7, levelRequirement = 58, },
		[17] = { 5, levelRequirement = 61, },
		[18] = { 2, levelRequirement = 64, },
		[19] = { 0, levelRequirement = 66, },
		[20] = { -2, levelRequirement = 68, },
		[21] = { -4, levelRequirement = 70, },
		[22] = { -7, levelRequirement = 72, },
		[23] = { -10, levelRequirement = 74, },
	},
}
skills["SkeletonProjectileCold"] = {
name = "冰霜投射物",
	hidden = true,
	color = 4,
	baseEffectiveness = 0.68180000782013,
	incrementalEffectiveness = 0.03940000012517,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.95,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"base_is_projectile",
		"spell_maximum_action_distance_+%",
	},
	statInterpolation = { 3, 3, 1, 1, },
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, 1, -60, critChance = 5, levelRequirement = 4, manaCost = 5, },
		[2] = { 0.80000001192093, 1.2000000476837, 1, -60, critChance = 5, levelRequirement = 19, manaCost = 4, },
		[3] = { 2.7000000476837, 4.210000038147, 1, -60, critChance = 5, levelRequirement = 68, manaCost = 4, },
	},
}
skills["SkeletonProjectileFire"] = {
name = "火焰投射物",
	hidden = true,
	color = 4,
	baseEffectiveness = 0.83329999446869,
	incrementalEffectiveness = 0.03940000012517,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.95,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_is_projectile",
		"spell_maximum_action_distance_+%",
	},
	statInterpolation = { 3, 3, 1, 1, },
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, 1, -60, critChance = 5, levelRequirement = 4, manaCost = 5, },
		[2] = { 0.80000001192093, 1.2000000476837, 1, -60, critChance = 5, levelRequirement = 19, manaCost = 4, },
		[3] = { 2.7000000476837, 4.210000038147, 1, -60, critChance = 5, levelRequirement = 68, manaCost = 4, },
	},
}
skills["SkeletonProjectileLightning"] = {
name = "闪电投射物",
	hidden = true,
	color = 4,
	baseEffectiveness = 0.9375,
	incrementalEffectiveness = 0.03940000012517,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.95,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"base_is_projectile",
		"spell_maximum_action_distance_+%",
	},
	statInterpolation = { 3, 3, 1, 1, },
	levels = {
		[1] = { 0.5, 1.5, 1, -60, critChance = 5, levelRequirement = 4, manaCost = 5, },
		[2] = { 0.5, 1.5, 1, -60, critChance = 5, levelRequirement = 19, manaCost = 4, },
		[3] = { 1.1699999570847, 3.4900000095367, 1, -60, critChance = 5, levelRequirement = 68, manaCost = 4, },
	},
}
skills["RockGolemSlam"] = {
name = "重击",
	hidden = true,
	color = 1,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"active_skill_attack_speed_+%_final",
		"chance_to_taunt_on_hit_%",
		"skill_art_variation",
		"active_skill_area_of_effect_radius_+%_final",
		"is_area_damage",
	},
	statInterpolation = { 1, 1, 1, 1, },
	levels = {
		[1] = { -20, 33, 1, 0, damageEffectiveness = 1.75, cooldown = 6, baseMultiplier = 1.75, levelRequirement = 1, },
	},
}
skills["RockGolemWhirlingBlades"] = {
name = "回旋之刃",
	hidden = true,
	color = 4,
	description = "迅速穿越敌人并同时造成武器伤害. 限定匕首, 爪以及单手剑. ",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MovementSkill] = true, [SkillType.TravelSkill] = true, },
	weaponTypes = {
		["Thrusting One Handed Sword"] = true,
		["Claw"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.43,
	baseFlags = {
		attack = true,
		melee = true,
		movement = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"skill_sound_variation",
		"active_skill_attack_speed_+%_final",
		"monster_flurry",
		"cast_time_overrides_attack_duration",
		"ignores_proximity_shield",
	},
	statInterpolation = { 1, 1, 1, },
	levels = {
		[1] = { 1, -50, 1, levelRequirement = 1, },
	},
}
skills["ZombieSlam"] = {
name = "重击",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
		skill("radius", 18),
	},
	qualityStats = {
	},
	stats = {
		"active_skill_attack_speed_+%_final",
		"active_skill_damage_+%_final",
		"base_skill_effect_duration",
		"is_area_damage",
		"global_always_hit",
	},
	statInterpolation = { 1, 1, 1, },
	levels = {
		[1] = { -22, 45, 280, cooldown = 5, levelRequirement = 1, },
	},
}
skills["SummonedSpiderViperStrike"] = {
	name = "毒蛇打击",
	hidden = true,
	color = 4,
	baseEffectiveness = 0.64999997615814,
	incrementalEffectiveness = 0.025499999523163,
	description = "击中敌人，额外造成等同于部分物理伤害的混沌伤害，并使敌人中毒。该技能受技能持续时间属性影响。限定爪类、匕首与剑类。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Duration] = true, [SkillType.AttackCanRepeat] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.DamageOverTime] = true, [SkillType.ChaosSkill] = true, },
	weaponTypes = {
		["Claw"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "debuff_skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"physical_damage_%_to_add_as_chaos",
		"base_chance_to_poison_on_hit_%",
		"base_skill_effect_duration",
		"poison_duration_is_skill_duration",
	},
	statInterpolation = { 1, 1, 1, },
	levels = {
		[1] = { 25, 100, 8000, levelRequirement = 1, },
	},
}
skills["DancingDervishCyclone"] = {
	name = "旋风斩",
	hidden = true,
	color = 2,
	description = "对周围敌人造成伤害, 接而进行一连串的旋转攻击, 边向目标地点前进边攻击路径上的敌人, 无法被多重打击和无情辅助.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Melee] = true, [SkillType.MovementSkill] = true, [SkillType.Type65] = true, },
	weaponTypes = {
		["None"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["Two Handed Sword"] = true,
		["Dagger"] = true,
		["Staff"] = true,
		["Two Handed Axe"] = true,
		["Two Handed Mace"] = true,
		["One Handed Axe"] = true,
		["Claw"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
	},
	baseMods = {
		skill("dpsMultiplier", 2),
		skill("radiusIsWeaponRange", true),
	},
	qualityStats = {
	},
	stats = {
		"physical_damage_+%",
		"attack_speed_+%",
		"skill_art_variation",
		"cyclone_movement_speed_+%_final",
		"cyclone_extra_distance",
		"active_skill_damage_+%_final",
		"is_area_damage",
	},
	statInterpolation = { 1, 1, 1, 1, 1, 1, },
	levels = {
		[1] = { 0, 20, 0, 0, 25, 0, levelRequirement = 1, },
	},
}
skills["SummonPhantasmFadingProjectile"] = {
name = "物理投射物",
	hidden = true,
	color = 4,
	baseEffectiveness = 1.0099999904633,
	incrementalEffectiveness = 0.048500001430511,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.Hit] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.17,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"base_is_projectile",
		"always_pierce",
	},
	statInterpolation = { 3, 3, },
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, damageEffectiveness = 1.5, critChance = 5, levelRequirement = 1, },
	},
}
skills["HeraldOfAgonyMinionMortar"] = {
name = "炮击",
	hidden = true,
	color = 4,
	description = "通用的怪物炮击技能. 与怪物投射物相似, 但带有冲击效果.",
	skillTypes = { [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Attack] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 2,
	baseFlags = {
		attack = true,
		projectile = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"projectile_spread_radius",
		"projectile_minimum_range",
		"number_of_additional_projectiles",
		"active_skill_attack_speed_+%_final",
		"main_hand_base_maximum_attack_distance",
		"is_area_damage",
		"base_is_projectile",
		"distribute_additional_projectiles_over_contact_points",
	},
	statInterpolation = { 1, 1, 1, 1, 1, },
	levels = {
		[1] = { 20, 10, 5, -35, 50, damageEffectiveness = 0.4, cooldown = 7.5, baseMultiplier = 0.4, levelRequirement = 1, },
	},
}
skills["HeraldOfAgonyMinionTailSpike"] = {
name = "尾刺",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.ProjectileAttack] = true, [SkillType.SkillCanMirageArcher] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Hit] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1.3,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"monster_projectile_variation",
		"base_projectile_speed_+%",
		"active_skill_attack_speed_+%_final",
		"number_of_additional_projectiles",
		"base_is_projectile",
	},
	statInterpolation = { 1, 1, 1, 1, },
	levels = {
		[1] = { 39, 0, 0, 4, levelRequirement = 1, },
	},
}
skills["HeraldOfAgonyMinionCleave"] = {
name = "横扫",
	hidden = true,
	color = 1,
	description = "在身体前方以弧状挥动武器（双持时则挥动两把武器）, 对前方区域的怪物造成伤害。限定斧类与剑类。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.AttackCanRepeat] = true, [SkillType.Melee] = true, [SkillType.Type53] = true, [SkillType.PhysicalSkill] = true, },
	weaponTypes = {
		["Two Handed Axe"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Two Handed Sword"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"is_area_damage",
	},
	statInterpolation = { },
	levels = {
		[1] = { levelRequirement = 1, },
	},
}
skills["HeraldOfLightMinionSlam"] = {
name = "重击",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"active_skill_attack_speed_+%_final",
		"is_area_damage",
	},
	statInterpolation = { 1, },
	levels = {
		[1] = { -33, levelRequirement = 1, },
	},
}
skills["SentinelHolySlam"] = {
name = "十字军猛击",
	hidden = true,
	color = 1,
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"active_skill_attack_speed_+%_final",
		"is_area_damage",
	},
	statInterpolation = { 1, },
	levels = {
		[1] = { -33, damageEffectiveness = 2, cooldown = 6, baseMultiplier = 2, levelRequirement = 0, },
	},
}
skills["RelicTriggeredNova"] = {
name = "新星",
	hidden = true,
	color = 4,
	baseEffectiveness = 0.89999997615814,
	incrementalEffectiveness = 0.064000003039837,
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	statMap = {
		["base_life_regeneration_rate_per_minute"] = {
mod("LifeRegen", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Aura", effectName = "圣物的祝福"}),
			div = 60,
		},
	},
	baseFlags = {
		spell = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"holy_relic_trigger_on_parent_attack_%",
		"base_life_regeneration_rate_per_minute",
		"base_skill_effect_duration",
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"minion_life_regeneration_rate_per_second",
	},
	statInterpolation = { 1, 1, 1, 3, 3, 1, },
	levels = {
		[1] = { 100, 209, 4000, 0.80000001192093, 1.2000000476837, 6, damageEffectiveness = 0.7, cooldown = 0.5, levelRequirement = 4, },
		[2] = { 100, 249, 4000, 0.80000001192093, 1.2000000476837, 8, damageEffectiveness = 0.74, cooldown = 0.5, levelRequirement = 6, },
		[3] = { 100, 317, 4000, 0.80000001192093, 1.2000000476837, 11, damageEffectiveness = 0.78, cooldown = 0.5, levelRequirement = 9, },
		[4] = { 100, 401, 4000, 0.80000001192093, 1.2000000476837, 14, damageEffectiveness = 0.82, cooldown = 0.5, levelRequirement = 12, },
		[5] = { 100, 534, 4000, 0.80000001192093, 1.2000000476837, 18, damageEffectiveness = 0.86, cooldown = 0.5, levelRequirement = 16, },
		[6] = { 100, 697, 4000, 0.80000001192093, 1.2000000476837, 25, damageEffectiveness = 0.9, cooldown = 0.5, levelRequirement = 20, },
		[7] = { 100, 891, 4000, 0.80000001192093, 1.2000000476837, 33, damageEffectiveness = 0.94, cooldown = 0.5, levelRequirement = 24, },
		[8] = { 100, 1119, 4000, 0.80000001192093, 1.2000000476837, 43, damageEffectiveness = 0.98, cooldown = 0.5, levelRequirement = 28, },
		[9] = { 100, 1381, 4000, 0.80000001192093, 1.2000000476837, 54, damageEffectiveness = 1.02, cooldown = 0.5, levelRequirement = 32, },
		[10] = { 100, 1681, 4000, 0.80000001192093, 1.2000000476837, 67, damageEffectiveness = 1.06, cooldown = 0.5, levelRequirement = 36, },
		[11] = { 100, 2019, 4000, 0.80000001192093, 1.2000000476837, 83, damageEffectiveness = 1.1, cooldown = 0.5, levelRequirement = 40, },
		[12] = { 100, 2399, 4000, 0.80000001192093, 1.2000000476837, 100, damageEffectiveness = 1.14, cooldown = 0.5, levelRequirement = 44, },
		[13] = { 100, 2821, 4000, 0.80000001192093, 1.2000000476837, 121, damageEffectiveness = 1.18, cooldown = 0.5, levelRequirement = 48, },
		[14] = { 100, 3288, 4000, 0.80000001192093, 1.2000000476837, 144, damageEffectiveness = 1.22, cooldown = 0.5, levelRequirement = 52, },
		[15] = { 100, 3690, 4000, 0.80000001192093, 1.2000000476837, 167, damageEffectiveness = 1.26, cooldown = 0.5, levelRequirement = 55, },
		[16] = { 100, 4122, 4000, 0.80000001192093, 1.2000000476837, 190, damageEffectiveness = 1.3, cooldown = 0.5, levelRequirement = 58, },
		[17] = { 100, 4587, 4000, 0.80000001192093, 1.2000000476837, 215, damageEffectiveness = 1.34, cooldown = 0.5, levelRequirement = 61, },
		[18] = { 100, 5085, 4000, 0.80000001192093, 1.2000000476837, 244, damageEffectiveness = 1.38, cooldown = 0.5, levelRequirement = 64, },
		[19] = { 100, 5616, 4000, 0.80000001192093, 1.2000000476837, 275, damageEffectiveness = 1.42, cooldown = 0.5, levelRequirement = 67, },
		[20] = { 100, 6183, 4000, 0.80000001192093, 1.2000000476837, 309, damageEffectiveness = 1.46, cooldown = 0.5, levelRequirement = 70, },
		[21] = { 100, 6625, 4000, 0.80000001192093, 1.2000000476837, 331, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 72, },
		[22] = { 100, 6949, 4000, 0.80000001192093, 1.2000000476837, 347, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 74, },
		[23] = { 100, 7281, 4000, 0.80000001192093, 1.2000000476837, 364, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 76, },
		[24] = { 100, 7621, 4000, 0.80000001192093, 1.2000000476837, 381, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 78, },
		[25] = { 100, 7969, 4000, 0.80000001192093, 1.2000000476837, 398, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 80, },
		[26] = { 100, 8325, 4000, 0.80000001192093, 1.2000000476837, 416, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 82, },
		[27] = { 100, 8689, 4000, 0.80000001192093, 1.2000000476837, 434, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 84, },
		[28] = { 100, 9060, 4000, 0.80000001192093, 1.2000000476837, 453, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 86, },
		[29] = { 100, 9440, 4000, 0.80000001192093, 1.2000000476837, 472, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 88, },
		[30] = { 100, 9828, 4000, 0.80000001192093, 1.2000000476837, 491, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 90, },
		[31] = { 100, 9926, 4000, 0.80000001192093, 1.2000000476837, 496, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 91, },
		[32] = { 100, 10026, 4000, 0.80000001192093, 1.2000000476837, 501, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 92, },
		[33] = { 100, 10127, 4000, 0.80000001192093, 1.2000000476837, 506, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 93, },
		[34] = { 100, 10229, 4000, 0.80000001192093, 1.2000000476837, 511, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 94, },
		[35] = { 100, 10331, 4000, 0.80000001192093, 1.2000000476837, 516, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 95, },
		[36] = { 100, 10436, 4000, 0.80000001192093, 1.2000000476837, 521, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 96, },
		[37] = { 100, 10541, 4000, 0.80000001192093, 1.2000000476837, 527, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 97, },
		[38] = { 100, 10646, 4000, 0.80000001192093, 1.2000000476837, 532, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 98, },
		[39] = { 100, 10754, 4000, 0.80000001192093, 1.2000000476837, 538, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 99, },
		[40] = { 100, 10862, 4000, 0.80000001192093, 1.2000000476837, 543, damageEffectiveness = 1.5, cooldown = 0.5, levelRequirement = 100, },
	},
}
skills["DominatingBlowMinionCharge"] = {
	name = "重盾冲锋",
	hidden = true,
	color = 4,
	description = "向目标区域或敌人冲锋，在路径上的敌人将会被推向两旁，并反复对你前方小范围区域内造成伤害。 抵达目标处时造成大范围伤害。伤害与击晕几率将视冲锋距离而定。无法被多重打击辅助。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Shield] = true, [SkillType.Melee] = true, [SkillType.Area] = true, [SkillType.MovementSkill] = true, [SkillType.TravelSkill] = true, },
	weaponTypes = {
		["None"] = true,
		["Claw"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"shield_charge_scaling_stun_threshold_reduction_+%_at_maximum_range",
		"base_movement_velocity_+%",
		"shield_charge_damage_+%_maximum",
		"ignores_proximity_shield",
		"global_cannot_crit",
	},
	statInterpolation = { 1, 1, 1, },
	levels = {
		[1] = { 25, 400, 30, cooldown = 4, levelRequirement = 1, },
	},
}
skills["SummonedRhoaShieldCharge"] = {
	name = "重盾冲锋",
	hidden = true,
	color = 4,
	description = "向目标区域或敌人冲锋，在路径上的敌人将会被推向两旁，并反复对你前方小范围区域内造成伤害。 抵达目标处时造成大范围伤害。伤害与击晕几率将视冲锋距离而定。无法被多重打击辅助。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Shield] = true, [SkillType.Melee] = true, [SkillType.Area] = true, [SkillType.MovementSkill] = true, [SkillType.TravelSkill] = true, },
	weaponTypes = {
		["None"] = true,
		["Claw"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
		["Thrusting One Handed Sword"] = true,
		["One Handed Axe"] = true,
		["Dagger"] = true,
		["One Handed Sword"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"shield_charge_scaling_stun_threshold_reduction_+%_at_maximum_range",
		"base_movement_velocity_+%",
		"shield_charge_damage_+%_maximum",
		"attack_speed_+%",
		"physical_damage_%_to_add_as_lightning",
		"shield_charge_extra_distance",
		"ignores_proximity_shield",
	},
	statInterpolation = { 1, 1, 1, 1, 1, 1, },
	levels = {
		[1] = { 50, 100, 10, 20, 15, 0, cooldown = 3, levelRequirement = 1, },
	},
}
skills["SummonedSnakeProjectile"] = {
name = "混沌投射物",
	hidden = true,
	color = 4,
	skillTypes = { [SkillType.Attack] = true, [SkillType.ProjectileAttack] = true, [SkillType.SkillCanMirageArcher] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Hit] = true, [SkillType.Triggerable] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"monster_projectile_variation",
		"base_is_projectile",
	},
	statInterpolation = { 1, },
	levels = {
		[1] = { 1, levelRequirement = 1, },
	},
}
skills["DropBearSummonedGroundSlam"] = {
	name = "裂地之击",
	hidden = true,
	color = 4,
	description = "以长杖或双手锤重击地面并制造出一道向前释放的冲击波, 被此冲击波击中的敌人将会受到伤害并有较高几率被击晕. 限定长杖与锤.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.AttackCanRepeat] = true, [SkillType.Melee] = true, },
	weaponTypes = {
		["Two Handed Mace"] = true,
		["Staff"] = true,
		["One Handed Mace"] = true,
		["Sceptre"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_stun_threshold_reduction_+%",
		"is_area_damage",
	},
	statInterpolation = { 1, },
	levels = {
		[1] = { 0, cooldown = 3, levelRequirement = 1, },
	},
}
skills["DropBearSummonedRallyingCry"] = {
	name = "激励战吼",
	hidden = true,
	color = 1,
	description = "施展战吼, 使自身和盟友伤害和魔力恢复增加. 伤害增加量随着周围敌人数量提升. 嘲讽周围所有敌人, 使他们攻击施放者. 与其他战吼技能共享技能冷却.",
	skillTypes = { [SkillType.Buff] = true, [SkillType.Area] = true, [SkillType.Duration] = true, [SkillType.Warcry] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.25,
	statMap = {
		["damage_+%"] = {
			mod("Damage", "INC", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff" }),
		},
	},
	baseFlags = {
		warcry = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("buffAllies", true),
	},
	qualityStats = {
	},
	stats = {
		"damage_+%",
		"base_skill_effect_duration",
		"base_deal_no_damage",
	},
	statInterpolation = { 1, 1, },
	levels = {
		[1] = { 25, 4000, cooldown = 5, levelRequirement = 1, },
	},
}
skills["MinionInstability"] = {
name = "召唤物聚能",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		fire = true,
	},
	skillTypes = { [10] = true, },
	baseMods = {
		skill("FireMin", 1, { type = "PerStat", stat = "Life", div = 1/.33 }),
		skill("FireMax", 1, { type = "PerStat", stat = "Life", div = 1/.33 }),
		skill("showAverage", true),
		skill("radius", 22),
	},
	qualityStats = {
	},
	levelMods = {
	},
	levels = {
		[1] = { },
	},
	stats = {
	},
	statLevels = {
	},
}
skills["BeaconCausticCloud"] = {
name = "腐蚀毒云",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		chaos = true,
	},
	skillTypes = { },
	baseMods = {
		skill("ChaosDot", 1, { type = "PerStat", stat = "Life", div = 10 }),
		skill("dotIsArea", true),
	},
	qualityStats = {
	},
	levelMods = {
	},
	levels = {
		[1] = { },
	},
	stats = {
	},
	statLevels = {
	},
}
skills["BeaconZombieCausticCloud"] = {
name = "腐蚀毒云",
	hidden = true,
	color = 4,
	baseFlags = {
		cast = true,
		area = true,
		chaos = true,
	},
	skillTypes = { },
	baseMods = {
		skill("ChaosDot", 1, { type = "PerStat", stat = "Life", div = 2 }),
		skill("dotIsArea", true),
	},
	qualityStats = {
	},
	levelMods = {
	},
	levels = {
		[1] = { },
	},
	stats = {
	},
	statLevels = {
	},
}



skills["SlavedriverFlameWhip"] = {
	name = "闪电鞭笞",
	hidden = true,
	color = 3,
	baseEffectiveness = 2.5,
	incrementalEffectiveness = 0.045000001788139,
	description = "释放怒焰之力对敌人进行攻击. 燃烧中的敌人将会受到更多伤害.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Triggerable] = true, [SkillType.Area] = true, [SkillType.FireSkill] = true, [SkillType.CanRapidFire] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.5,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"active_skill_area_of_effect_radius_+%_final",
		"base_cast_speed_+%",
		"is_area_damage",
	},
	statInterpolation = { 3, 3, 1, 1, },
	levels = {
		[1] = { 0.5, 1.5, 50, -65, critChance = 6, levelRequirement = 1, },
	},
}
skills["KitavaSlavedriverFlameWhip"] = {
	name = "物理鞭笞",
	hidden = true,
	color = 3,
	baseEffectiveness = 2.2000000476837,
	incrementalEffectiveness = 0.027499999850988,
	description = "释放怒焰之力对敌人进行攻击. 燃烧中的敌人将会受到更多伤害.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Triggerable] = true, [SkillType.Area] = true, [SkillType.FireSkill] = true, [SkillType.CanRapidFire] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.5,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"active_skill_area_of_effect_radius_+%_final",
		"base_cast_speed_+%",
		"is_area_damage",
	},
	statInterpolation = { 3, 3, 1, 1, },
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, 50, -65, critChance = 6, levelRequirement = 1, },
	},
}
