-- This file is automatically generated, do not edit!
-- Path of Building
--
-- Other active skills
-- Skill data (c) Grinding Gear Games
--
local skills, mod, flag, skill = ...

skills["Melee"] = {
name = "默认攻击",
	hidden = true,
	color = 4,
	description = "对你的敌人无情痛击.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.ProjectileAttack] = true, [SkillType.SkillCanMirageArcher] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.AttackCanRepeat] = true, [SkillType.Melee] = true, [SkillType.SkillCanVolley] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
	},
	levels = {
		[1] = { 1, 1, levelRequirement = 1, statInterpolation = { 1, 1, }, },
	},
}
skills["MeleeUseContactPoint"] = {
name = "默认攻击",
	hidden = true,
	color = 4,
	description = "对你的敌人无情痛击.",
	skillTypes = { [SkillType.Attack] = true, [SkillType.ProjectileAttack] = true, [SkillType.SkillCanMirageArcher] = true, [SkillType.Projectile] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.AttackCanRepeat] = true, [SkillType.Melee] = true, [SkillType.SkillCanVolley] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		melee = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"skill_can_fire_arrows",
		"skill_can_fire_wand_projectiles",
		"use_scaled_contact_offset",
		"projectile_uses_contact_position",
	},
	levels = {
		[1] = { levelRequirement = 1, statInterpolation = { }, },
	},
}
skills["GemDetonateMines"] = {
	name = "引爆地雷",
	color = 4,
	description = "引爆一个地雷，启动传爆序列。它将持续引爆周围的地雷。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.Triggerable] = true, [SkillType.Instant] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0,
	baseFlags = {
		spell = true,
	},
	baseMods = {
	},
	qualityStats = {
		{ "mine_detonation_speed_+%", 1 },
	},
	stats = {
		"display_mine_deontation_mechanics_detonation_speed_+%_final_per_sequence_mine",
		"base_deal_no_damage",
	},
	levels = {
		[1] = { 10, cooldown = 0.2, levelRequirement = 8, statInterpolation = { 1, }, },
		[2] = { 10, cooldown = 0.2, levelRequirement = 8, statInterpolation = { 1, }, },
		[3] = { 10, cooldown = 0.2, levelRequirement = 8, statInterpolation = { 1, }, },
		[4] = { 10, cooldown = 0.2, levelRequirement = 8, statInterpolation = { 1, }, },
		[5] = { 10, cooldown = 0.2, levelRequirement = 8, statInterpolation = { 1, }, },
		[6] = { 10, cooldown = 0.2, levelRequirement = 8, statInterpolation = { 1, }, },
		[7] = { 10, cooldown = 0.2, levelRequirement = 8, statInterpolation = { 1, }, },
		[8] = { 10, cooldown = 0.2, levelRequirement = 8, statInterpolation = { 1, }, },
		[9] = { 10, cooldown = 0.2, levelRequirement = 8, statInterpolation = { 1, }, },
		[10] = { 10, cooldown = 0.2, levelRequirement = 8, statInterpolation = { 1, }, },
	},
}
skills["Portal"] = {
	name = "时空之门",
	color = 4,
	description = "开启一个连接城镇的时空之门.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.Triggerable] = true, [SkillType.Type27] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 2.5,
	baseFlags = {
		spell = true,
	},
	baseMods = {
	},
	qualityStats = {
		{ "base_cast_speed_+%", 3 },
	},
	stats = {
		"base_deal_no_damage",
	},
	levels = {
		[1] = { levelRequirement = 10, statInterpolation = { }, },
		[2] = { levelRequirement = 10, statInterpolation = { }, },
		[3] = { levelRequirement = 10, statInterpolation = { }, },
		[4] = { levelRequirement = 10, statInterpolation = { }, },
		[5] = { levelRequirement = 10, statInterpolation = { }, },
		[6] = { levelRequirement = 10, statInterpolation = { }, },
		[7] = { levelRequirement = 10, statInterpolation = { }, },
		[8] = { levelRequirement = 10, statInterpolation = { }, },
		[9] = { levelRequirement = 10, statInterpolation = { }, },
		[10] = { levelRequirement = 10, statInterpolation = { }, },
	},
}
skills["VaalBreach"] = {
	name = "瓦尔.裂隙",
	color = 4,
	description = "创造一个裂隙, 使你能够遭遇裂隙中强大的敌人. ",
	skillTypes = { [SkillType.Spell] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.Type27] = true, [SkillType.Vaal] = true, [SkillType.CantUseFistOfWar] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 2.5,
	baseFlags = {
		spell = true,
	},
	baseMods = {
	},
	qualityStats = {
		{ "base_cast_speed_+%", 3 },
	},
	stats = {
		"base_deal_no_damage",
		"display_vaal_breach_no_drops_xp",
		"cannot_cancel_skill_before_contact_point",
	},
	levels = {
		[1] = { levelRequirement = 10, statInterpolation = { }, },
		[2] = { levelRequirement = 10, statInterpolation = { }, },
		[3] = { levelRequirement = 10, statInterpolation = { }, },
		[4] = { levelRequirement = 10, statInterpolation = { }, },
		[5] = { levelRequirement = 10, statInterpolation = { }, },
		[6] = { levelRequirement = 10, statInterpolation = { }, },
		[7] = { levelRequirement = 10, statInterpolation = { }, },
		[8] = { levelRequirement = 10, statInterpolation = { }, },
		[9] = { levelRequirement = 10, statInterpolation = { }, },
		[10] = { levelRequirement = 10, statInterpolation = { }, },
	},
}
skills["SupportUniqueMjolnerLightningSpellsCastOnHit"] = {
name = "沉默之雷",
	hidden = true,
	color = 4,
	support = true,
	requireSkillTypes = { SkillType.Spell, SkillType.LightningSkill, SkillType.Triggerable, SkillType.AND, SkillType.AND, },
	addSkillTypes = { SkillType.Triggered, SkillType.Type90, },
	excludeSkillTypes = { SkillType.Trap, SkillType.Mine, SkillType.Totem, SkillType.Aura, SkillType.TriggeredGrantedSkill, },
	statDescriptionScope = "gem_stat_descriptions",
	fromItem = true,
	statMap = {
		["triggered_spell_spell_damage_+%"] = {
			mod("Damage", "INC", nil, ModFlag.Spell, 0, { type = "Condition", var = "SkillIsTriggered" }),
		},
	},
	baseMods = {
		skill("showAverage", true),
	},
	qualityStats = {
	},
	stats = {
		"triggered_spell_spell_damage_+%",
		"unique_mjolner_lightning_spells_triggered",
		"socketed_triggered_skills_use_weapon_attack_time_for_pvp_scaling",
	},
	levels = {
		[1] = { 100, cooldown = 0.15, levelRequirement = 0, statInterpolation = { 1, }, },
	},
}
skills["SupportAuraDuration"] = {
name = "祝福",
	hidden = true,
	color = 1,
	support = true,
	requireSkillTypes = { SkillType.CanHaveBlessing, },
	addSkillTypes = { SkillType.Duration, },
	excludeSkillTypes = { SkillType.Totem, },
	statDescriptionScope = "gem_stat_descriptions",
	fromItem = true,
	statMap = {
		["support_aura_duration_base_buff_duration"] = {
			skill("auraDuration", nil),
			div = 1000,
		},
		["support_aura_duration_base_reserve_duration"] = {
			skill("reserveDuration", nil),
			div = 1000,
		},
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"support_aura_duration_base_buff_duration",
		"support_aura_duration_base_reserve_duration",
		"non_curse_aura_effect_+%",
		"base_spell_cast_time_ms_override",
	},
	levels = {
		[25] = { 11400, 200, 12, 500, levelRequirement = 80, statInterpolation = { 1, 1, 1, 1, }, },
	},
}
skills["SupportUniqueCosprisMaliceColdSpellsCastOnMeleeCriticalStrike"] = {
name = "卡普里的意志",
	hidden = true,
	color = 4,
	support = true,
	requireSkillTypes = { SkillType.Spell, SkillType.ColdSkill, SkillType.Triggerable, SkillType.AND, SkillType.AND, },
	addSkillTypes = { SkillType.Triggered, SkillType.Type90, },
	excludeSkillTypes = { SkillType.Trap, SkillType.Mine, SkillType.Totem, SkillType.Aura, SkillType.TriggeredGrantedSkill, },
	statDescriptionScope = "gem_stat_descriptions",
	fromItem = true,
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"unique_cospris_malice_cold_spells_triggered",
		"socketed_triggered_skills_use_weapon_attack_time_for_pvp_scaling",
	},
	levels = {
		[1] = { cooldown = 0.15, levelRequirement = 1, statInterpolation = { }, },
	},
}
skills["RepeatingShockwave"] = {
	name = "重复冲击波",
	hidden = true,
	color = 4,
	description = "此技能在你移动中仍然会持续释放冲击波",
	skillTypes = { [SkillType.Area] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.FireSkill] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"base_chance_to_ignite_%",
		"cast_on_gain_skill",
		"cannot_knockback",
		"spell_uncastable_if_triggerable",
		"is_area_damage",
		"skill_can_add_multiple_charges_per_action",
	},
	levels = {
		[7] = { 50, 75, 10, critChance = 5, levelRequirement = 1, statInterpolation = { 1, 1, 1, }, },
	},
}
skills["BirdAspect"] = {
	name = "鸟之势",
	hidden = true,
	color = 4,
	description = "当生效时，依次轮流赋予玩家鸟之力量和鸟之斗魄。鸟之力量会让你和你的召唤生物被击中后短时间内有一定几率造成双倍伤害。鸟之斗魄会让你和你的召唤生物移动速度增加。",
	skillTypes = { [SkillType.Buff] = true, [SkillType.ManaCostPercent] = true, [SkillType.Spell] = true, [SkillType.ManaCostReserved] = true, [SkillType.Duration] = true, [SkillType.Instant] = true, [SkillType.Type85] = true, [SkillType.Type86] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0,
	fromItem = true,
	statMap = {
		["chance_to_deal_double_damage_%"] = {
mod("DoubleDamageChance", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff", effectName = "鸟之力量", effectCond = "AviansMightActive" }),
		},
		["base_movement_velocity_+%"] = {
mod("MovementSpeed", "INC", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff", effectName = "鸟之斗魄", effectCond = "AviansFlightActive" }),
		},
		["minion_movement_speed_+%"] = {
		},
	},
	baseFlags = {
		cast = true,
		duration = true,
	},
	baseMods = {
		skill("buffMinions", true),
	},
	qualityStats = {
	},
	stats = {
		"chance_to_deal_double_damage_%",
		"minion_chance_to_deal_double_damage_%",
		"base_movement_velocity_+%",
		"minion_movement_speed_+%",
		"base_skill_effect_duration",
		"base_secondary_skill_effect_duration",
	},
	levels = {
		[20] = { 10, 10, 10, 10, 4000, 4000, cooldown = 0.5, levelRequirement = 1, manaCost = 25, statInterpolation = { 1, 1, 1, 1, 1, 1, }, },
	},
}
skills["CatAspect"] = {
	name = "猫之势",
	hidden = true,
	color = 4,
	description = "当生效时，依次轮流赋予玩家猫之隐匿和猫之敏捷。猫之隐匿会提高暴击率，短时间内有一定几率避免伤害，并使你更难被敌人发现。猫之敏捷会在一段时间内增加你的攻击和施法速度。",
	skillTypes = { [SkillType.Buff] = true, [SkillType.ManaCostPercent] = true, [SkillType.Spell] = true, [SkillType.ManaCostReserved] = true, [SkillType.Duration] = true, [SkillType.Instant] = true, [SkillType.Type85] = true, [SkillType.Type86] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0,
	fromItem = true,
	statMap = {
		["critical_strike_chance_+%"] = {
mod("CritChance", "INC", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff", effectName = "猫之隐匿", effectCond = "CatsStealthActive" }),
		},
		["attack_speed_+%_granted_from_skill"] = {
mod("Speed", "INC", nil, ModFlag.Attack, 0, { type = "GlobalEffect", effectType = "Buff", effectName = "猫之敏捷", effectCond = "CatsAgilityActive" }),
		},
		["cast_speed_+%_granted_from_skill"] = {
mod("Speed", "INC", nil, ModFlag.Cast, 0, { type = "GlobalEffect", effectType = "Buff", effectName = "猫之敏捷", effectCond = "CatsAgilityActive" }),
		},
	},
	baseFlags = {
		cast = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"critical_strike_chance_+%",
		"avoid_damage_%",
		"enemy_aggro_radius_+%",
		"attack_speed_+%_granted_from_skill",
		"cast_speed_+%_granted_from_skill",
		"base_skill_effect_duration",
		"base_secondary_skill_effect_duration",
	},
	levels = {
		[20] = { 100, 15, -50, 10, 10, 4000, 6000, cooldown = 0.5, levelRequirement = 1, manaCost = 25, statInterpolation = { 1, 1, 1, 1, 1, 1, 1, }, },
	},
}
skills["CrabAspect"] = {
	name = "蟹之势",
	hidden = true,
	color = 4,
	description = "当生效时，每隔一段时间获得深海屏障，每个深海屏障使你获得额外物理伤害减少。所有的深海屏障会在你受到物理伤害时失去。",
	skillTypes = { [SkillType.Buff] = true, [SkillType.ManaCostPercent] = true, [SkillType.Spell] = true, [SkillType.ManaCostReserved] = true, [SkillType.Instant] = true, [SkillType.PhysicalSkill] = true, [SkillType.Type85] = true, [SkillType.Type86] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0,
	fromItem = true,
	statMap = {
		["physical_damage_reduction_%_per_crab_aspect_stack"] = {
			mod("PhysicalDamageReduction", "BASE", nil, 0, 0, { type = "Multiplier", var = "CrabBarrier" }, { type = "GlobalEffect", effectType = "Buff" }),
		},
		["max_crab_aspect_stacks"] = {
			mod("CrabBarriersMax", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff" }),
		},
	},
	baseFlags = {
		cast = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"physical_damage_reduction_%_per_crab_aspect_stack",
		"max_crab_aspect_stacks",
	},
	levels = {
		[20] = { 2, 10, cooldown = 0.5, levelRequirement = 1, manaCost = 25, statInterpolation = { 1, 1, }, },
	},
}
skills["SpiderAspect"] = {
	name = "蛛之势",
	hidden = true,
	color = 4,
	description = "当生效时，每隔一段时间对周围敌人施加蜘蛛网减益效果，并减缓他们的移动速度。每层敌人身上的蜘蛛网会增加他们受到的伤害。",
	skillTypes = { [SkillType.Buff] = true, [SkillType.ManaCostPercent] = true, [SkillType.Spell] = true, [SkillType.ManaCostReserved] = true, [SkillType.Duration] = true, [SkillType.Instant] = true, [SkillType.Type85] = true, [SkillType.Type86] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "debuff_skill_stat_descriptions",
	castTime = 0,
	fromItem = true,
	statMap = {
		["base_movement_velocity_+%"] = {
		},
		["base_damage_taken_+%"] = {
mod("DamageTaken", "INC", nil, 0, 0, { type = "GlobalEffect", effectType = "Debuff", effectName = "蜘蛛网" })
		},
		["spider_aspect_max_web_count"] = {
			mod("Multiplier:SpiderWebApplyStackMax", "BASE", nil),
		},
	},
	baseFlags = {
		cast = true,
		duration = true,
	},
	baseMods = {
		skill("debuff", true),
		skill("stackCount", 1, { type = "Multiplier", var = "SpiderWebApplyStack", limitVar = "SpiderWebApplyStackMax" }),
	},
	qualityStats = {
	},
	stats = {
		"base_movement_velocity_+%",
		"base_damage_taken_+%",
		"base_skill_effect_duration",
		"spider_aspect_web_interval_ms",
		"spider_aspect_max_web_count",
	},
	levels = {
		[20] = { -30, 5, 6000, 1000, 3, cooldown = 0.5, levelRequirement = 1, manaCost = 25, statInterpolation = { 1, 1, 1, 1, 1, }, },
	},
}
skills["BloodOffering"] = {
	name = "血脉奉献",
	hidden = true,
	color = 3,
	description = "消耗一具灵柩，牺牲你的一部分生命，根据牺牲量给予你的召唤生物生命回复以及伤害加成的效果。技能会消耗附近的灵柩，每消耗一具灵柩就会增加持续时间和生命回复。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Buff] = true, [SkillType.Duration] = true, [SkillType.Triggerable] = true, [SkillType.Minion] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanMine] = true, [SkillType.SkillCanTotem] = true, },
	statDescriptionScope = "offering_skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	statMap = {
		["damage_+%"] = {
			mod("Damage", "INC", nil, 0, 0, { type = "GlobalEffect", effectType = "Buff" }),
		},
	},
	baseFlags = {
		spell = true,
		duration = true,
	},
	baseMods = {
		skill("buffMinions", true),
		skill("buffNotPlayer", true),
	},
	qualityStats = {
		{ "skill_effect_duration_+%", 0.5 },
	},
	stats = {
		"base_skill_effect_duration",
		"offering_skill_effect_duration_per_corpse",
		"blood_offering_%_of_life_to_lose",
		"blood_offering_%_of_lost_life_to_regenerate_as_life_per_second",
		"blood_offering_life_regenerated_+%_final_per_corpse",
		"damage_+%",
		"base_deal_no_damage",
	},
	levels = {
		[15] = { 5000, 1000, 20, 35, 10, 50, levelRequirement = 12, statInterpolation = { 1, 1, 1, 1, 1, 1, }, },
	},
}
skills["TriggeredBoneNova"] = {
	name = "裂骨新星",
	hidden = true,
	color = 4,
	description = "向你周围爆发骨刺，造成物理伤害。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.ProjectileAttack] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Hit] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"number_of_additional_projectiles",
		"attack_trigger_on_hitting_bleeding_enemy_%",
		"monster_projectile_variation",
		"projectiles_nova",
		"spell_uncastable_if_triggerable",
		"base_is_projectile",
		"cannot_cause_bleeding",
	},
	levels = {
		[20] = { 8, 100, 15, cooldown = 0.5, levelRequirement = 1, statInterpolation = { 1, 1, 1, }, },
	},
}
skills["ColdAegis"] = {
	name = "凝冰守护",
	hidden = true,
	color = 4,
	description = "灵唤一个守护护盾，在消散前抵挡击中造成的冰霜伤害。该护盾在一段时间未受到冰霜伤害后会自动回复满值。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"aegis_unique_shield_max_value",
		"active_skill_display_aegis_variation",
		"cast_on_gain_skill",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[20] = { 1000, 1, levelRequirement = 1, statInterpolation = { 1, 1, }, },
	},
}
skills["TriggeredConsecrate"] = {
name = "奉献地面",
	hidden = true,
	color = 4,
	description = "创造一片奉献地面, 恢复其中的友军（包括你自己）生命. ",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Duration] = true, [SkillType.Triggerable] = true, [SkillType.Area] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.AreaSpell] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		duration = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"life_regeneration_rate_per_minute_%",
		"cast_on_crit_%",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[10] = { 5000, 360, 100, cooldown = 5, levelRequirement = 1, statInterpolation = { 1, 1, 1, }, },
	},
}
skills["TriggeredSummonLesserShrine"] = {
	name = "创造低等神殿",
	hidden = true,
	color = 4,
	description = "创造一个低等神殿, 触摸即可获得加成. 使用后或是放置一段时间后低等神殿即会消失. 技能冷却开始生效. ",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.Duration] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"chance_to_cast_on_kill_%",
		"base_skill_effect_duration",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[1] = { 100, 10000, cooldown = 20, levelRequirement = 1, statInterpolation = { 1, 1, }, },
	},
}
skills["ChaosDegenAuraUnique"] = {
	name = "死神光环",
	hidden = true,
	color = 4,
	description = "施放一个光环对周围敌人造成持续混沌伤害. 该技能无法被图腾施放.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Buff] = true, [SkillType.Area] = true, [SkillType.DamageOverTime] = true, [SkillType.Aura] = true, [SkillType.AuraDebuff] = true, [SkillType.ChaosSkill] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "aura_skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		aura = true,
	},
	baseMods = {
		skill("dotIsArea", true),
	},
	qualityStats = {
	},
	stats = {
		"base_chaos_damage_to_deal_per_minute",
		"cast_on_gain_skill",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[20] = { 33750, levelRequirement = 62, statInterpolation = { 1, }, },
	},
}
skills["DeathWalk"] = {
	name = "泯灭之舞",
	hidden = true,
	color = 4,
	description = "在你移动时，该技能会引爆周围的灵柩，造成火焰范围伤害。灵柩的爆炸无法被法术伤害词缀加成，并且该伤害无法被反射。",
	skillTypes = { [SkillType.Area] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.FireSkill] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		cast = true,
		area = true,
		chaos = true,
	},
	baseMods = {
		skill("explodeCorpse", true),
		skill("showAverage", true),
	},
	qualityStats = {
	},
	stats = {
		"corpse_explosion_monster_life_%",
		"cast_on_gain_skill",
		"cannot_knockback",
		"spell_uncastable_if_triggerable",
		"is_area_damage",
		"skill_can_add_multiple_charges_per_action",
		"damage_cannot_be_reflected",
	},
	levels = {
		[20] = { 5, levelRequirement = 60, statInterpolation = { 1, }, },
	},
}
skills["TouchOfGod"] = {
	name = "多里亚尼之触",
	hidden = true,
	color = 1,
	description = "角色以拳头敲击前方的地面, 攻速较慢, 伤害较高. 该攻击能对大范围内的敌人造成闪电伤害, 并有几率对其造成感电效果. 持有武器时无法使用. ",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.LightningSkill] = true, [SkillType.Melee] = true, [SkillType.AttackCanRepeat] = true, [SkillType.Slam] = true, },
	weaponTypes = {
		["None"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
		melee = true,
	},
	baseMods = {
	},
	qualityStats = {
		{ "area_damage_+%", 0.5 },
	},
	stats = {
		"skill_physical_damage_%_to_convert_to_lightning",
		"active_skill_attack_speed_+%_final",
		"base_chance_to_shock_%",
		"is_area_damage",
		"global_always_hit",
	},
	levels = {
		[1] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 28, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[2] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 31, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[3] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 34, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[4] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 37, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[5] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 40, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[6] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 42, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[7] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 44, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[8] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 46, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[9] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 48, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[10] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 50, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[11] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 52, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[12] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 54, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[13] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 56, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[14] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 58, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[15] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 60, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[16] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 62, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[17] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 64, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[18] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 66, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[19] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 68, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[20] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 70, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[21] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 72, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[22] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 74, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[23] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 76, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[24] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 78, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[25] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 80, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[26] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 82, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[27] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 84, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[28] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 86, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[29] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 88, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[30] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 90, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[31] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 91, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[32] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 92, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[33] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 93, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[34] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 94, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[35] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 95, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[36] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 96, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[37] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 97, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[38] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 98, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[39] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 99, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
		[40] = { 100, -30, 40, damageEffectiveness = 6, levelRequirement = 100, manaCost = 8, statInterpolation = { 1, 1, 1, }, },
	},
}
skills["ElementalAegis"] = {
	name = "元素守护",
	hidden = true,
	color = 4,
	description = "灵唤一个守护护盾，在消散前抵挡击中造成的元素伤害。该护盾在一段时间未受到元素伤害后会自动回复满值。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"aegis_unique_shield_max_value",
		"active_skill_display_aegis_variation",
		"cast_on_gain_skill",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[20] = { 1000, 2, levelRequirement = 1, statInterpolation = { 1, 1, }, },
	},
}
skills["SupportElementalPenetration"] = {
name = "元素穿透",
	hidden = true,
	color = 3,
	support = true,
	requireSkillTypes = { SkillType.Hit, SkillType.Attack, },
	addSkillTypes = { },
	excludeSkillTypes = { },
	statDescriptionScope = "gem_stat_descriptions",
	fromItem = true,
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"reduce_enemy_elemental_resistance_%",
	},
	levels = {
		[20] = { 37, manaMultiplier = 40, levelRequirement = 70, statInterpolation = { 1, }, },
	},
}
skills["OnHitWhileCursedTriggeredCurseNova"] = {
	name = "元素守卫",
	hidden = true,
	color = 4,
	baseEffectiveness = 3,
	incrementalEffectiveness = 0.050000000745058,
	description = "向所有方向发射投射物，将它们的所有物理伤害转化成随机元素伤害，并一段时间内使你免疫诅咒。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.FireSkill] = true, [SkillType.ColdSkill] = true, [SkillType.LightningSkill] = true, [SkillType.Duration] = true, [SkillType.Buff] = true, [SkillType.PhysicalSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	parts = {
		{
name = "转化为火焰",
		},
		{
name = "转化为冰霜",
		},
		{
name = "转化为闪电",
		},
	},
	baseFlags = {
		spell = true,
		projectile = true,
		duration = true,
	},
	baseMods = {
		mod("SkillPhysicalDamageConvertToFire", "BASE", 100, 0, 0, { type = "SkillPart", skillPart = 1 }),
		mod("SkillPhysicalDamageConvertToCold", "BASE", 100, 0, 0, { type = "SkillPart", skillPart = 2 }),
		mod("SkillPhysicalDamageConvertToLightning", "BASE", 100, 0, 0, { type = "SkillPart", skillPart = 3 }),
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"number_of_additional_projectiles",
		"elemental_strike_physical_damage_%_to_convert",
		"cast_on_melee_hit_if_cursed_%",
		"base_skill_effect_duration",
		"base_is_projectile",
		"projectiles_nova",
		"spell_uncastable_if_triggerable",
		"disable_visual_hit_effect",
	},
	levels = {
		[20] = { 0.80000001192093, 1.2000000476837, 16, 100, 100, 3000, critChance = 7, cooldown = 1, levelRequirement = 70, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
	},
}
skills["Envy"] = {
	name = "嫉妒",
	hidden = true,
	color = 3,
	baseEffectiveness = 2.0999999046326,
	incrementalEffectiveness = 0.023000000044703,
	description = "施放一个光环, 使你与受光环影响友军在攻击和施放法术时额外附带混沌伤害.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Area] = true, [SkillType.Buff] = true, [SkillType.ManaCostReserved] = true, [SkillType.Type27] = true, [SkillType.ManaCostPercent] = true, [SkillType.SkillCanTotem] = true, [SkillType.Aura] = true, [SkillType.ChaosSkill] = true, [SkillType.Instant] = true, [SkillType.AreaSpell] = true, [SkillType.Type85] = true, [SkillType.Type86] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "aura_skill_stat_descriptions",
	castTime = 0,
	fromItem = true,
	statMap = {
		["attack_minimum_added_chaos_damage"] = {
			mod("ChaosMin", "BASE", nil, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["attack_maximum_added_chaos_damage"] = {
			mod("ChaosMax", "BASE", nil, 0, KeywordFlag.Attack, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["spell_minimum_added_chaos_damage"] = {
			mod("ChaosMin", "BASE", nil, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }),
		},
		["spell_maximum_added_chaos_damage"] = {
			mod("ChaosMax", "BASE", nil, 0, KeywordFlag.Spell, { type = "GlobalEffect", effectType = "Aura" }),
		},
	},
	baseFlags = {
		spell = true,
		aura = true,
		area = true,
		chaos = true,
	},
	baseMods = {
		skill("radius", 40),
	},
	qualityStats = {
	},
	stats = {
		"attack_minimum_added_chaos_damage",
		"attack_maximum_added_chaos_damage",
		"active_skill_base_radius_+",
		"spell_minimum_added_chaos_damage",
		"spell_maximum_added_chaos_damage",
		"base_deal_no_damage",
	},
	levels = {
		[15] = { 0.5, 0.69999998807907, 14, 0.44999998807907, 0.60000002384186, cooldown = 1.2, levelRequirement = 60, manaCost = 50, statInterpolation = { 3, 3, 1, 3, 3, }, },
	},
}
skills["FireAegis"] = {
	name = "烈焰守护",
	hidden = true,
	color = 4,
	description = "灵唤一个守护护盾，在消散前抵挡击中造成的火焰伤害。该护盾在一段时间未受到火焰伤害后会自动回复满值。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"aegis_unique_shield_max_value",
		"active_skill_display_aegis_variation",
		"cast_on_gain_skill",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[20] = { 1000, 0, levelRequirement = 1, statInterpolation = { 1, 1, }, },
	},
}
skills["FireBurstOnHit"] = {
	name = "火焰爆破",
	hidden = true,
	color = 4,
	baseEffectiveness = 2.333300113678,
	incrementalEffectiveness = 0.037999998778105,
	description = "喷发出一道火焰, 造成火焰伤害.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Area] = true, [SkillType.Hit] = true, [SkillType.FireSkill] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_fire_damage",
		"spell_maximum_base_fire_damage",
		"cast_on_hit_%",
		"is_area_damage",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 1, statInterpolation = { 3, 3, 1, }, },
		[2] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 2, statInterpolation = { 3, 3, 1, }, },
		[3] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 4, statInterpolation = { 3, 3, 1, }, },
		[4] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 7, statInterpolation = { 3, 3, 1, }, },
		[5] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 11, statInterpolation = { 3, 3, 1, }, },
		[6] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 16, statInterpolation = { 3, 3, 1, }, },
		[7] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 20, statInterpolation = { 3, 3, 1, }, },
		[8] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 24, statInterpolation = { 3, 3, 1, }, },
		[9] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 28, statInterpolation = { 3, 3, 1, }, },
		[10] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 32, statInterpolation = { 3, 3, 1, }, },
		[11] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 36, statInterpolation = { 3, 3, 1, }, },
		[12] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 40, statInterpolation = { 3, 3, 1, }, },
		[13] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 44, statInterpolation = { 3, 3, 1, }, },
		[14] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 48, statInterpolation = { 3, 3, 1, }, },
		[15] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 52, statInterpolation = { 3, 3, 1, }, },
		[16] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 56, statInterpolation = { 3, 3, 1, }, },
		[17] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 60, statInterpolation = { 3, 3, 1, }, },
		[18] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 64, statInterpolation = { 3, 3, 1, }, },
		[19] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 67, statInterpolation = { 3, 3, 1, }, },
		[20] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 70, statInterpolation = { 3, 3, 1, }, },
		[21] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 72, statInterpolation = { 3, 3, 1, }, },
		[22] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 74, statInterpolation = { 3, 3, 1, }, },
		[23] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 76, statInterpolation = { 3, 3, 1, }, },
		[24] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 78, statInterpolation = { 3, 3, 1, }, },
		[25] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 80, statInterpolation = { 3, 3, 1, }, },
		[26] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 82, statInterpolation = { 3, 3, 1, }, },
		[27] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 84, statInterpolation = { 3, 3, 1, }, },
		[28] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 86, statInterpolation = { 3, 3, 1, }, },
		[29] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 88, statInterpolation = { 3, 3, 1, }, },
		[30] = { 0.80000001192093, 1.2000000476837, 10, damageEffectiveness = 1.3, cooldown = 0.5, critChance = 5, levelRequirement = 90, statInterpolation = { 3, 3, 1, }, },
	},
}
skills["VaalAuraElementalDamageHealing"] = {
	name = "元素之愈",
	hidden = true,
	color = 4,
	description = "施展治愈你和友方的灵气, 治愈量等同所受的元素伤害量. ",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Buff] = true, [SkillType.Area] = true, [SkillType.Duration] = true, [SkillType.SkillCanTotem] = true, [SkillType.Vaal] = true, [SkillType.Aura] = true, [SkillType.AreaSpell] = true, [SkillType.Instant] = true, [SkillType.Type85] = true, [SkillType.Type86] = true, [SkillType.Type90] = true, [SkillType.CantUseFistOfWar] = true, },
	statDescriptionScope = "aura_skill_stat_descriptions",
	castTime = 0,
	fromItem = true,
	baseFlags = {
		spell = true,
		aura = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("radius", 40),
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"base_elemental_damage_heals",
		"cannot_gain_souls",
		"modifiers_to_buff_effect_duration_also_affect_soul_prevention_duration",
		"immune_to_curses",
	},
	levels = {
		[20] = { 5000, cooldown = 0.5, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["IcestormUniqueStaff12"] = {
	name = "冰风暴",
	hidden = true,
	color = 3,
	description = "冰箭如雨般洒落在目标区域. 落地时将会爆炸, 对周围敌人造成伤害并冰缓它们, 并造成冰结地面. 技能伤害以智慧数值为基础.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.Duration] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Triggerable] = true, [SkillType.ColdSkill] = true, [SkillType.SpellCanCascade] = true, [SkillType.ChillingArea] = true, [SkillType.CanRapidFire] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.75,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("duration", 0.15, { type = "PerStat", stat = "Int", div = 100, base = 1.5 }),
		skill("radius", 25),
		skill("radiusSecondary", 10),
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_cold_damage_+_per_10_intelligence",
		"spell_maximum_base_cold_damage_+_per_10_intelligence",
		"base_skill_effect_duration",
		"fire_storm_fireball_delay_ms",
		"skill_override_pvp_scaling_time_ms",
		"firestorm_drop_ground_ice_duration_ms",
		"skill_art_variation",
		"skill_effect_duration_per_100_int",
		"base_skill_show_average_damage_instead_of_dps",
		"is_area_damage",
	},
	levels = {
		[1] = { 1, 3, 1500, 100, 450, 500, 4, 150, damageEffectiveness = 0.45, critChance = 6, levelRequirement = 1, manaCost = 22, statInterpolation = { 1, 1, 1, 1, 1, 1, 1, 1, }, },
	},
}
skills["TriggeredIcicleNova"] = {
	name = "爆环冰刺",
	hidden = true,
	color = 4,
	description = "从被击败的敌人周围发射一圈寒冰投射物，并将造成的所有物理伤害转化为冰霜伤害。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.ProjectileAttack] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Hit] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.ColdSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
		skill("showAverage", true),
	},
	qualityStats = {
	},
	stats = {
		"number_of_additional_projectiles",
		"trigger_on_kill_vs_frozen_enemy_%",
		"monster_projectile_variation",
		"skill_physical_damage_%_to_convert_to_cold",
		"projectiles_nova",
		"spell_uncastable_if_triggerable",
		"base_is_projectile",
		"never_freeze",
	},
	levels = {
		[20] = { 8, 100, 38, 100, cooldown = 0.5, levelRequirement = 1, statInterpolation = { 1, 1, 1, 1, }, },
	},
}
skills["MerveilWarp"] = {
	name = "幻象传送",
	hidden = true,
	color = 4,
	description = "传送至指定目的地. 起点跟终点产生一圈冰缓地面.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.MovementSkill] = true, [SkillType.Duration] = true, [SkillType.ColdSkill] = true, [SkillType.Area] = true, [SkillType.AreaSpell] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.6,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
	},
	levels = {
		[20] = { 1500, cooldown = 3, levelRequirement = 1, manaCost = 20, statInterpolation = { 1, }, },
	},
}
skills["LightningAegis"] = {
	name = "闪电神盾",
	hidden = true,
	color = 4,
	description = "召唤一个守护护盾，在消散前抵挡击中造成的闪电伤害。该护盾在一段时间未受到闪电伤害后会自动回复满值。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"aegis_unique_shield_max_value",
		"active_skill_display_aegis_variation",
		"cast_on_gain_skill",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[20] = { 1000, 3, levelRequirement = 1, statInterpolation = { 1, 1, }, },
	},
}
skills["LightningSpell"] = {
	name = "雷霆万钧",
	hidden = true,
	color = 3,
	baseEffectiveness = 5,
	incrementalEffectiveness = 0.029999999329448,
	description = "使用雷击攻击一个区域, 造成闪电伤害.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Triggered] = true, [SkillType.LightningSkill] = true, [SkillType.Area] = true, [SkillType.Hit] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_lightning_damage",
		"spell_maximum_base_lightning_damage",
		"cast_on_crit_%",
		"is_area_damage",
		"spell_uncastable_if_triggerable",
	},
		levels = {
		[1] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 1, statInterpolation = { 3, 3, 1, }, },
		[2] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 2, statInterpolation = { 3, 3, 1, }, },
		[3] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 4, statInterpolation = { 3, 3, 1, }, },
		[4] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 7, statInterpolation = { 3, 3, 1, }, },
		[5] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 11, statInterpolation = { 3, 3, 1, }, },
		[6] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 16, statInterpolation = { 3, 3, 1, }, },
		[7] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 20, statInterpolation = { 3, 3, 1, }, },
		[8] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 24, statInterpolation = { 3, 3, 1, }, },
		[9] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 28, statInterpolation = { 3, 3, 1, }, },
		[10] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 32, statInterpolation = { 3, 3, 1, }, },
		[11] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 36, statInterpolation = { 3, 3, 1, }, },
		[12] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 40, statInterpolation = { 3, 3, 1, }, },
		[13] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 44, statInterpolation = { 3, 3, 1, }, },
		[14] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 48, statInterpolation = { 3, 3, 1, }, },
		[15] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 52, statInterpolation = { 3, 3, 1, }, },
		[16] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 56, statInterpolation = { 3, 3, 1, }, },
		[17] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 60, statInterpolation = { 3, 3, 1, }, },
		[18] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 64, statInterpolation = { 3, 3, 1, }, },
		[19] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 67, statInterpolation = { 3, 3, 1, }, },
		[20] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 70, statInterpolation = { 3, 3, 1, }, },
		[21] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 72, statInterpolation = { 3, 3, 1, }, },
		[22] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 74, statInterpolation = { 3, 3, 1, }, },
		[23] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 76, statInterpolation = { 3, 3, 1, }, },
		[24] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 78, statInterpolation = { 3, 3, 1, }, },
		[25] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 80, statInterpolation = { 3, 3, 1, }, },
		[26] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 82, statInterpolation = { 3, 3, 1, }, },
		[27] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 84, statInterpolation = { 3, 3, 1, }, },
		[28] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 86, statInterpolation = { 3, 3, 1, }, },
		[29] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 88, statInterpolation = { 3, 3, 1, }, },
		[30] = { 0.5, 1.5, 100, damageEffectiveness = 2, cooldown = 0.2, critChance = 7.5, levelRequirement = 90, statInterpolation = { 3, 3, 1, }, },
	},
}
skills["UniqueAnimateWeapon"] = {
	name = "幻化之刃德尔维希",
	hidden = true,
	color = 4,
	description = "召唤幻化之刃德尔维希, 当它存在时你获得猛攻, 但武器失效. ",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.Triggerable] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.Type72] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, [SkillType.Triggered] = true, },
	minionSkillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Area] = true, [SkillType.MovementSkill] = true, [SkillType.AttackCanRepeat] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	minionList = {
		"UniqueAnimatedWeapon",
	},
	minionUses = {
		["Weapon 1"] = true,
	},
	statMap = {
		["attack_damage_+%"] = {
			mod("MinionModifier", "LIST", { mod = mod("Damage", "INC", nil, ModFlag.Attack) }),
		},
		["attack_speed_+%"] = {
			mod("MinionModifier", "LIST", { mod = mod("Speed", "INC", nil, ModFlag.Attack) }),
		},
	},
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
		mod("DisableWeapons", "FLAG", true, 0, 0, { type = "GlobalEffect", effectType = "Buff" }),
		mod("Condition:Onslaught", "FLAG", true, 0, 0, { type = "GlobalEffect", effectType = "Buff" }),
		skill("minionLevel", 59),
	},
	qualityStats = {
	},
	stats = {
		"disable_weapons",
		"attack_speed_+%",
		"attack_damage_+%",
		"chance_to_cast_on_rampage_tier_%",
		"minion_movement_speed_+%",
		"minion_grants_rampage_kill_to_parent_on_hitting_unique_enemy_%",
	},
	levels = {
		[15] = { 1, 25, 110, 100, 30, 25, cooldown = 0.5, levelRequirement = 1, statInterpolation = { 1, 1, 1, 1, 1, 1, }, },
	},
}
skills["TriggeredMoltenStrike"] = {
	name = " 熔岩爆破",
	hidden = true,
	color = 1,
	description = "对目标造成物理及火焰伤害, 并在挥击的途中从武器弹射出熔岩球. 这些熔岩球在着地时会爆炸, 并对附近的敌人造成伤害. ",
	skillTypes = { [SkillType.Projectile] = true, [SkillType.Attack] = true, [SkillType.Area] = true, [SkillType.FireSkill] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.ProjectileAttack] = true, [SkillType.Type83] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"number_of_additional_projectiles",
		"attack_trigger_on_melee_hit_%",
		"show_number_of_projectiles",
		"base_is_projectile",
		"is_area_damage",
		"base_skill_show_average_damage_instead_of_dps",
	},
	levels = {
		[16] = { 2, 20, damageEffectiveness = 1.15, cooldown = 0.15, baseMultiplier = 1.15, levelRequirement = 1, statInterpolation = { 1, 1, }, },
	},
}
skills["TriggeredSummonSpider"] = {
	name = "召唤毒蛛",
	hidden = true,
	color = 3,
	description = "周遭每具灵柩召唤两只幽魂巨蛛, 他们将扑向你的敌人. 敌人将不会主动攻击你的蜘蛛.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Minion] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.CreatesMinion] = true, },
	minionSkillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.AttackCanRepeat] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	minionList = {
		"SpiderMinion",
	},
	statMap = {
		["summoned_spider_grants_attack_speed_+%"] = {
mod("Speed", "INC", nil, ModFlag.Attack, 0, { type = "Multiplier", var = "RaisedSpider" }, { type = "GlobalEffect", effectType = "Buff", effectName = "豢养蜘蛛" }),
		},
		["summoned_spider_grants_poison_damage_+%"] = {
mod("Damage", "INC", nil, 0, KeywordFlag.Poison, { type = "Multiplier", var = "RaisedSpider" }, { type = "GlobalEffect", effectType = "Buff", effectName = "豢养蜘蛛" }),
		},
	},
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"chance_to_cast_on_kill_%_target_self",
		"base_skill_effect_duration",
		"number_of_spider_minions_allowed",
		"summoned_spider_grants_attack_speed_+%",
		"summoned_spider_grants_poison_damage_+%",
		"damage_+%_vs_players",
		"spell_uncastable_if_triggerable",
		"take_no_actions_while_parent_dead",
		"minion_dies_when_parent_dies",
		"minions_cannot_taunt_enemies",
	},
	levels = {
		[1] = { 100, 30000, 20, 2, 12, -85, cooldown = 2, levelRequirement = 75, statInterpolation = { 1, 1, 1, 1, 1, 1, }, },
	},
}
skills["ShadeForm"] = {
	name = "暗影姿态",
	hidden = true,
	color = 4,
	description = "在一段时间内使你对物理伤害免疫，同时很难被敌人发现。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Duration] = true, [SkillType.Buff] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.PhysicalSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"enemy_aggro_radius_+%",
		"trigger_on_skill_use_from_chest_%",
	},
	levels = {
		[20] = { 3000, -50, 20, cooldown = 45, levelRequirement = 1, statInterpolation = { 1, 1, 1, }, },
	},
}
skills["TriggeredShockedGround"] = {
	name = "电击地面",
	hidden = true,
	color = 4,
	description = "在你周围创造一片电击地面. ",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, [SkillType.Duration] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.LightningSkill] = true, [SkillType.AreaSpell] = true, [SkillType.NovaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"cast_when_hit_%",
		"skill_art_variation",
		"base_skill_effect_duration",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[10] = { 100, 7, 5000, cooldown = 5, levelRequirement = 1, statInterpolation = { 1, 1, 1, }, },
	},
}
skills["SpiritBurst"] = {
	name = "精神冲击",
	hidden = true,
	color = 3,
	baseEffectiveness = 1.875,
	incrementalEffectiveness = 0.03999999910593,
	description = "消耗一个精神能量球发射一个投射物并造成物理伤害。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.PhysicalSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
	},
	baseMods = {
		skill("showAverage", true),
	},
	qualityStats = {
	},
	stats = {
		"trigger_on_skill_use_%_if_you_have_a_spirit_charge",
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"number_of_additional_projectiles",
		"spell_uncastable_if_triggerable",
		"base_is_projectile",
		"projectiles_nova",
	},
	levels = {
		[20] = { 100, 0.80000001192093, 1.2000000476837, 6, damageEffectiveness = 1.2, critChance = 6, levelRequirement = 70, statInterpolation = { 1, 3, 3, 1, }, },
	},
}
skills["StormCascadeTriggered"] = {
	name = "风暴突袭",
	hidden = true,
	color = 3,
	baseEffectiveness = 1.7555999755859,
	incrementalEffectiveness = 0.034600000828505,
	description = "放出一连串会爆裂的小雷球, 每个对撞上的敌人造成范围伤害.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Triggerable] = true, [SkillType.LightningSkill] = true, [SkillType.PhysicalSkill] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.AreaSpell] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.8,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
	},
	baseMods = {
		skill("showAverage", true),
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"upheaval_number_of_spikes",
		"skill_physical_damage_%_to_convert_to_lightning",
		"active_skill_base_radius_+",
		"cast_on_attack_use_%",
		"is_area_damage",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[1] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 28, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[2] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 31, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[3] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 34, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[4] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 37, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[5] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 40, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[6] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 42, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[7] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 44, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[8] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 46, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[9] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 48, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[10] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 50, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[11] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 52, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[12] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 54, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[13] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 56, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[14] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 58, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[15] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 60, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[16] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 62, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[17] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 64, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[18] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 66, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[19] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 68, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[20] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 70, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[21] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 72, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[22] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 74, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[23] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 76, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[24] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 78, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[25] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 80, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[26] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 82, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[27] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 84, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[28] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 86, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[29] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 88, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
		[30] = { 0.80000001192093, 1.2000000476837, 5, 60, 3, 100, critChance = 5, cooldown = 0.5, levelRequirement = 90, statInterpolation = { 3, 3, 1, 1, 1, 1, }, },
	},
}
skills["SummonBeastialRhoa"] = {
	name = "召唤兽化恐喙鸟",
	hidden = true,
	color = 3,
	description = "召唤一个兽化恐喙鸟.  兽化恐喙鸟能进行近战攻击并拥有冲锋技能.而且附带能恐吓敌人的光环. 兽化恐喙鸟的攻击无法被闪避.",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	minionSkillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.AttackCanRepeat] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	minionList = {
		"RhoaUniqueSummoned",
	},
	statMap = {
		["base_number_of_beast_minions_allowed"] = {
			mod("ActiveBeastMinionLimit", "BASE", nil),
		},
	},
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
		skill("allowTotemBuff", true),
		flag("Condition:HaveBestialMinion", { type = "GlobalEffect", effectType = "Buff" }),
	},
	qualityStats = {
		{ "minion_maximum_life_+%", 1 },
		{ "minion_damage_+%", 1 },
	},
	stats = {
		"base_actor_scale_+%",
		"base_number_of_beast_minions_allowed",
		"minion_maximum_life_+%",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"alternate_minion",
	},
	levels = {
		[20] = { 0, 1, 30, 12, 70, 0, cooldown = 5, levelRequirement = 70, manaCost = 30, statInterpolation = { 1, 1, 1, 1, 1, 1, }, },
	},
}
skills["SummonBeastialSnake"] = {
	name = "召唤兽化巨蛇",
	hidden = true,
	color = 3,
	description = "召唤一个兽化巨蛇. 兽化巨蛇的攻击能射出强大的混沌投射物. 兽化巨蛇的攻击无法被闪避.",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	minionSkillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.AttackCanRepeat] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Chaining] = true, [SkillType.ProjectileAttack] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	minionList = {
		"SnakeSpitUniqueSummoned",
	},
	statMap = {
		["base_number_of_beast_minions_allowed"] = {
			mod("ActiveBeastMinionLimit", "BASE", nil),
		},
	},
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
		skill("allowTotemBuff", true),
		flag("Condition:HaveBestialMinion", { type = "GlobalEffect", effectType = "Buff" }),
	},
	qualityStats = {
		{ "minion_maximum_life_+%", 1 },
		{ "minion_damage_+%", 1 },
	},
	stats = {
		"base_actor_scale_+%",
		"base_number_of_beast_minions_allowed",
		"minion_maximum_life_+%",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"alternate_minion",
	},
	levels = {
		[20] = { 0, 1, 30, 14, 70, 2, cooldown = 5, levelRequirement = 70, manaCost = 30, statInterpolation = { 1, 1, 1, 1, 1, 1, }, },
	},
}
skills["SummonBeastialUrsa"] = {
	name = "召唤兽化之爪",
	hidden = true,
	color = 3,
	description = "召唤一个兽化之爪. 兽化之爪能进行近战攻击并拥有裂地之击技能.而且附带激励战吼. 兽化之爪的攻击无法被闪避.",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	minionSkillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.AttackCanRepeat] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	minionList = {
		"DropBearUniqueSummoned",
	},
	statMap = {
		["base_number_of_beast_minions_allowed"] = {
			mod("ActiveBeastMinionLimit", "BASE", nil),
		},
	},
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
		skill("allowTotemBuff", true),
		flag("Condition:HaveBestialMinion", { type = "GlobalEffect", effectType = "Buff" }),
	},
	qualityStats = {
		{ "minion_maximum_life_+%", 1 },
		{ "minion_damage_+%", 1 },
	},
	stats = {
		"base_actor_scale_+%",
		"base_number_of_beast_minions_allowed",
		"minion_maximum_life_+%",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"alternate_minion",
	},
	levels = {
		[20] = { 0, 1, 30, 13, 70, 1, cooldown = 5, levelRequirement = 70, manaCost = 30, statInterpolation = { 1, 1, 1, 1, 1, 1, }, },
	},
}
skills["SummonEssenceSpirits"] = {
	name = "幽鬼之灵 ",
	hidden = true,
	color = 3,
	description = "召唤三个不会受到伤害的幽鬼之灵快速冲向并攻击附近的敌人. 敌人无法解除幽鬼之灵, 并且可以穿过幽鬼之灵.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Minion] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.CreatesMinion] = true, },
	minionSkillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.AttackCanRepeat] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	minionList = {
		"SummonedEssenceSpirit",
	},
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"active_skill_minion_added_damage_+%_final",
		"number_of_monsters_to_summon",
		"cast_on_gain_skill",
		"spell_uncastable_if_triggerable",
		"take_no_actions_while_parent_dead",
		"minion_dies_when_parent_dies",
		"minions_cannot_taunt_enemies",
	},
	levels = {
		[1] = { -15, 3, levelRequirement = 1, statInterpolation = { 1, 1, }, },
		[2] = { -15, 3, levelRequirement = 2, statInterpolation = { 1, 1, }, },
		[3] = { -15, 3, levelRequirement = 4, statInterpolation = { 1, 1, }, },
		[4] = { -15, 3, levelRequirement = 7, statInterpolation = { 1, 1, }, },
		[5] = { -15, 3, levelRequirement = 11, statInterpolation = { 1, 1, }, },
		[6] = { -15, 3, levelRequirement = 16, statInterpolation = { 1, 1, }, },
		[7] = { -15, 3, levelRequirement = 20, statInterpolation = { 1, 1, }, },
		[8] = { -15, 3, levelRequirement = 24, statInterpolation = { 1, 1, }, },
		[9] = { -15, 3, levelRequirement = 28, statInterpolation = { 1, 1, }, },
		[10] = { -15, 3, levelRequirement = 32, statInterpolation = { 1, 1, }, },
		[11] = { -15, 3, levelRequirement = 36, statInterpolation = { 1, 1, }, },
		[12] = { -15, 3, levelRequirement = 40, statInterpolation = { 1, 1, }, },
		[13] = { -15, 3, levelRequirement = 44, statInterpolation = { 1, 1, }, },
		[14] = { -15, 3, levelRequirement = 48, statInterpolation = { 1, 1, }, },
		[15] = { -15, 3, levelRequirement = 52, statInterpolation = { 1, 1, }, },
		[16] = { -15, 3, levelRequirement = 56, statInterpolation = { 1, 1, }, },
		[17] = { -15, 3, levelRequirement = 60, statInterpolation = { 1, 1, }, },
		[18] = { -15, 3, levelRequirement = 64, statInterpolation = { 1, 1, }, },
		[19] = { -15, 3, levelRequirement = 67, statInterpolation = { 1, 1, }, },
		[20] = { -15, 3, levelRequirement = 70, statInterpolation = { 1, 1, }, },
		[21] = { -15, 3, levelRequirement = 72, statInterpolation = { 1, 1, }, },
		[22] = { -15, 3, levelRequirement = 74, statInterpolation = { 1, 1, }, },
		[23] = { -15, 3, levelRequirement = 76, statInterpolation = { 1, 1, }, },
		[24] = { -15, 3, levelRequirement = 78, statInterpolation = { 1, 1, }, },
		[25] = { -15, 3, levelRequirement = 80, statInterpolation = { 1, 1, }, },
		[26] = { -15, 3, levelRequirement = 82, statInterpolation = { 1, 1, }, },
		[27] = { -15, 3, levelRequirement = 84, statInterpolation = { 1, 1, }, },
		[28] = { -15, 3, levelRequirement = 86, statInterpolation = { 1, 1, }, },
		[29] = { -15, 3, levelRequirement = 88, statInterpolation = { 1, 1, }, },
		[30] = { -15, 3, levelRequirement = 90, statInterpolation = { 1, 1, }, },
	},
}
skills["SummonHarbingerOfTheArcane"] = {
	name = "召唤秘法先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的秘法先驱者. 先驱者偶尔会对你施放秘术增强, 额外增加法术总伤害, 施法总速度和魔力回复总速度",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 0, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["SummonHarbingerOfBrutality"] = {
	name = "召唤残暴先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的残暴先驱者. 先驱者偶尔会对你施放一个增益, 显著增加伤害, 攻击速度, 移动速度并减少你受到的伤害.",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 5, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["SummonHarbingerOfDirections"] = {
	name = "召唤射术先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的射术先驱者. 先驱者会对你施放随机增益, 附加以下任意一个或全部效果: 1 个额外投射物, +1 连锁, 穿透 1 个额外目标, 投射物分裂.",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 3, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["SummonHarbingerOfFocus"] = {
	name = "召唤不屈先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的不屈先驱者. 在你持续吟唱时, 先驱者偶尔会对你施放一个增益, 减少你受到的伤害, 使你免疫所有晕眩和异常状态.",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 2, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["SummonHarbingerOfStorms"] = {
	name = "召唤冰雷先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的冰雷先驱者. 先驱者偶尔会冰缓或感电敌人并连锁到附近的敌人.",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	minionSkillTypes = { [SkillType.NonHitChill] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 4, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["SummonHarbingerOfTime"] = {
	name = "召唤时空先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的时空先驱者. 先驱者偶尔会对你施放迅捷之域, 增加你和你周围所有敌我单位的行动速度.",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 1, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["TriggeredSummonGhostOnKill"] = {
	name = "召唤幻灵",
	hidden = true,
	color = 3,
	description = "召唤一个幻灵，它会使用穿刺投射物法术，造成物理伤害。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Minion] = true, [SkillType.Duration] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.CreatesMinion] = true, },
	minionSkillTypes = { [SkillType.Duration] = true, [SkillType.Projectile] = true, [SkillType.Spell] = true, [SkillType.Hit] = true, [SkillType.PhysicalSkill] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	minionList = {
		"SummonedPhantasm",
	},
	statMap = {
		["base_number_of_support_ghosts_allowed"] = {
			mod("ActivePhantasmLimit", "BASE", nil),
		},
	},
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
		{ "chance_to_summon_support_ghost_on_killing_blow_%", 0.5 },
	},
	stats = {
		"trigger_on_corpse_consume_%_chance",
		"base_skill_effect_duration",
		"base_number_of_support_ghosts_allowed",
		"phantasm_minimum_added_physical_damage_to_grant",
		"phantasm_maximum_added_physical_damage_to_grant",
		"skill_can_own_support_ghosts",
		"skill_has_trigger_from_unique_item",
	},
	levels = {
		[20] = { 100, 15000, 10, 28, 43, manaMultiplier = 20, levelRequirement = 70, statInterpolation = { 1, 1, 1, 1, 1, }, },
	},
}
skills["SummonRigwaldsPack"] = {
	name = "召唤幽狼",
	hidden = true,
	color = 4,
	description = "召唤一匹幽狼攻击周围的敌人, 并在一段时间内死亡. ",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Minion] = true, [SkillType.Duration] = true, [SkillType.CreateMinion] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanMine] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.CreatesMinion] = true, },
	minionSkillTypes = { [SkillType.Attack] = true, [SkillType.Melee] = true, [SkillType.MeleeSingleTarget] = true, [SkillType.AttackCanRepeat] = true, },
	statDescriptionScope = "minion_spell_skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	minionList = {
		"SummonedSpectralWolf",
	},
	baseFlags = {
		spell = true,
		minion = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_skill_effect_duration",
		"number_of_wolves_allowed",
		"chance_to_cast_on_kill_%_target_self",
		"display_minion_monster_type",
		"display_minion_monster_level",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[18] = { 30000, 20, 10, 8, 65, levelRequirement = 66, statInterpolation = { 1, 1, 1, 1, 1, }, },
	},
}
skills["SummonVoidSphere"] = {
name = "召唤异动奇点",
	hidden = true,
	color = 3,
	baseEffectiveness = 3.4818000793457,
	incrementalEffectiveness = 0.035599999129772,
	description = "制造一个奇点并向最近的敌人移动，过程中发出造成范围冰霜伤害的冰爆。并留下一个漩涡, 对于在其中的敌人继续造成持续冰霜伤害和冰缓.。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.Duration] = true, [SkillType.Area] = true, [SkillType.Hit] = true, [SkillType.ColdSkill] = true, [SkillType.ChillingArea] = true, [SkillType.AreaSpell] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		area = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"chance_to_cast_on_kill_%",
		"base_skill_effect_duration",
		"base_secondary_skill_effect_duration",
		"ground_maelstrom_art_variation",
		"chilled_ground_base_magnitude_override",
		"spell_minimum_base_cold_damage",
		"spell_maximum_base_cold_damage",
		"base_cold_damage_to_deal_per_minute",
		"is_area_damage",
		"base_skill_show_average_damage_instead_of_dps",
		"spell_damage_modifiers_apply_to_skill_dot",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[20] = { 20, 8000, 4000, 5, 10, 0.80000001192093, 1.2000000476837, 83.333335195979, cooldown = 2, levelRequirement = 70, statInterpolation = { 1, 1, 1, 1, 1, 3, 3, 3, }, },
	},
}
skills["TentacleSmash"] = {
	name = "藤蔓抽击",
	hidden = true,
	color = 4,
	description = "制造 3 条巨大的藤蔓砸向地面造成一定范围内的武器伤害。每条藤蔓造成一定范围的攻击伤害。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		attack = true,
		area = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"attack_trigger_on_kill_%",
		"is_area_damage",
		"attack_unusable_if_triggerable",
	},
	levels = {
		[20] = { 20, baseMultiplier = 2.5, cooldown = 2, levelRequirement = 70, statInterpolation = { 1, }, },
	},
}

skills["VoidGaze"] = {
	name = "虚空凝视",
	hidden = true,
	color = 3,
	description = "对敌人施加一个减益, 移除他们部分混沌抗性.",
	skillTypes = { [SkillType.Spell] = true, [SkillType.ChaosSkill] = true, [SkillType.Area] = true, [SkillType.SkillCanTotem] = true, [SkillType.Duration] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.Triggerable] = true, [SkillType.AreaSpell] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "debuff_skill_stat_descriptions",
	castTime = 0.21,
	fromItem = true,
	statMap = {
		["base_chaos_damage_resistance_%"] = {
			mod("ChaosResist", "BASE", nil, 0, 0, { type = "GlobalEffect", effectType = "Debuff" }),
		},
	},

	baseFlags = {
		spell = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"base_chaos_damage_resistance_%",
		"base_skill_effect_duration",
		"cast_on_skill_use_%",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[10] = { -20, 10000, 100, cooldown = 2, levelRequirement = 40, statInterpolation = { 1, 1, 1, }, },
	},
}



--lucifer


skills["VoidShot"] = {
	name = "虚空射击",
	hidden = true,
	color = 4,
	description = "射出一根箭矢并减速飞向目标。箭矢会在飞出后变得不稳定最后爆炸并在范围内造成武器伤害，将一般的物理伤害转化为冰霜伤害。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.Projectile] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.ColdSkill] = true, [SkillType.SkillCanVolley] = true, },
	weaponTypes = {
		["Bow"] = true,
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		attack = true,
		projectile = true,
		area = true,
		duration = true,
	},
	baseMods = {
		skill("showAverage", true),
	},
	qualityStats = {
	},
	stats = {
		"trigger_on_skill_use_%_if_you_have_a_void_arrow",
		"skill_physical_damage_%_to_convert_to_cold",
		"active_skill_area_damage_+%_final",
		"base_is_projectile",
		"skill_can_fire_arrows",
		"base_skill_show_average_damage_instead_of_dps",
		"attack_unusable_if_triggerable",
	},
	levels = {
		[20] = { 100, 50, 100, damageEffectiveness = 1.2, baseMultiplier = 1.2, levelRequirement = 70, statInterpolation = { 1, 1, 1, }, },
	},
}

skills["SupportGreaterSpellEcho"] = {
name = "高等施法回响",
	hidden = true,
	color = 3,
	support = true,
	requireSkillTypes = { SkillType.SpellCanRepeat, },
	addSkillTypes = { },
	excludeSkillTypes = { SkillType.Totem, SkillType.Trap, SkillType.Mine, SkillType.Triggered, SkillType.ManaCostReserved, SkillType.Vaal, SkillType.Instant, },
	statDescriptionScope = "gem_stat_descriptions",
fromItem = true,
	 statMap = {
        ["support_greater_spell_echo_spell_damage_+%_final_per_repeat"] = {
            mod("Damage", "MORE", nil, ModFlag.Spell, 0, { type = "Multiplier", var = "spellEchoCount" }),
        },
        ["support_greater_spell_echo_area_of_effect_+%_per_repeat"] = {
            mod("AreaOfEffect", "MORE", nil, 0, 0, { type = "Multiplier", var = "spellEchoCount" }),
        },
    }, 
	baseMods = {
	},
	qualityStats = {
		{ "base_cast_speed_+%", 0.5 },
	},
	stats = {
		"base_spell_repeat_count",
		"support_greater_spell_echo_spell_damage_+%_final_per_repeat",
		"support_greater_spell_echo_area_of_effect_+%_per_repeat",
	},
	levels = {
		[30] = { 2, 35, 50, manaMultiplier = 50, levelRequirement = 90, statInterpolation = { 1, 1, 1, }, },
	},
}

skills["CreateFungalGroundOnKill"] = {
	name = "玷污",
	hidden = true,
	color = 4,
	description = "在目标地点创造一小片真菌地表。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Area] = true, [SkillType.Duration] = true, [SkillType.Triggerable] = true, [SkillType.TriggeredGrantedSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	fromItem = true,
	baseFlags = {
		spell = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"chance_to_cast_on_kill_%",
		"base_deal_no_damage",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[10] = { 100, levelRequirement = 1, duration = 5, cooldown = 1, statInterpolation = { 1, }, },
	},
}


skills["ChannelledSnipe"] = {
	name = "狙击",
	hidden = true,
	color = 2,
	secondaryGrantedEffectId = "ChannelledSnipeSupport",
	description = "持续吟唱给弓箭充能，积累层数。释放时，每层都会触发一种链接的弓类技能。这种方式不能触发持续吟唱技能。若没有链接任何技能，又至少积累了一层效果，则该技能会发射它原本的箭矢。无法用于图腾。",
	skillTypes = { [SkillType.Attack] = true, [SkillType.ProjectileAttack] = true, [SkillType.SkillCanMirageArcher] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Channelled] = true, },
	weaponTypes = {
		["Bow"] = true,
	},
	 
	statMap = {
		["snipe_triggered_skill_ailment_damage_+%_final_per_stage"] = {
			mod("Damage", "MORE", nil, 0, KeywordFlag.Ailment, { type = "Multiplier", var = "SnipeStage" }),
		},
		["snipe_triggered_skill_hit_damage_+%_final_per_stage"] = {
			mod("Damage", "MORE", nil, 0, KeywordFlag.Hit, { type = "Multiplier", var = "SnipeStage" }),
		},
		
		 
	},
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	baseFlags = {
		attack = true,
		projectile = true,
	},
	baseMods = {
		flag("Condition:CanSnipeStage"),
		mod("Dummy", "DUMMY", 1, 0, 0, { type = "Condition", var = "CanSnipeStage" }),
	},
	qualityStats = {
	},
	stats = {
		"snipe_max_stacks",
		"override_turn_duration_ms",
		"snipe_triggered_skill_ailment_damage_+%_final_per_stage",
		"snipe_triggered_skill_hit_damage_+%_final_per_stage",
		"skill_can_fire_arrows",
		"is_snipe_default_projectile",
		"is_snipe_default_projectile_2",
	},
	levels = {
		[20] = { 6, 100, 120, 165, attackSpeedMultiplier = 80, levelRequirement = 70, manaCost = 4, statInterpolation = { 1, 1, 1, 1, }, },
	},
}


skills["ChannelledSnipeSupport"] = {
	name = "狙击吟唱（辅）",
	hidden = true,
	color = 2,
	support = true,
	requireSkillTypes = { SkillType.ProjectileAttack, SkillType.Type56, SkillType.OR, SkillType.Triggerable, SkillType.AND, },
	addSkillTypes = { SkillType.Triggered, SkillType.Type90, },
	excludeSkillTypes = { SkillType.Totem, SkillType.Trap, SkillType.Mine, SkillType.ManaCostReserved, SkillType.Vaal, SkillType.Instant, SkillType.Channelled, },
	statDescriptionScope = "gem_stat_descriptions",
	statMap = {
	
	 
		 ["skill_triggered_by_snipe"] = {
			flag("Condition:CanSnipeStage"),
			mod("Dummy", "DUMMY", 1, 0, 0, { type = "Condition", var = "CanSnipeStage" }),
		},
		 ["snipe_triggered_skill_ailment_damage_+%_final_per_stage"] = {
			mod("Damage", "MORE", nil, 0, KeywordFlag.Ailment, { type = "Multiplier", var = "SnipeStage" }),
		},
		["snipe_triggered_skill_hit_damage_+%_final_per_stage"] = {
			mod("Damage", "MORE", nil, 0, KeywordFlag.Hit, { type = "Multiplier", var = "SnipeStage" }),
		},
	},
	baseMods = {
		mod("Damage", "MORE", -33),
		 
	},
	qualityStats = {
	},
	stats = {
		"snipe_triggered_skill_damage_+%_final",
		"snipe_triggered_skill_ailment_damage_+%_final_per_stage",
		"snipe_triggered_skill_hit_damage_+%_final_per_stage",
		"skill_triggered_by_snipe",
	},
	levels = {
		[20] = { 0, 120, 165, cooldown = 0.05, levelRequirement = 0, statInterpolation = { 1, 1, 1, }, },
	},
}


skills["BrandDetonate"] = {
	name = "烙印喷涌",
	hidden = true,
	color = 3,
	baseEffectiveness = 5.5,
	incrementalEffectiveness = 0.03999999910593,
	description = "使你在目标区域附近的烙印超载，让它们更快激活，也更快耗尽。被超载的烙印耗尽时对一片区域造成伤害。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Triggerable] = true, [SkillType.PhysicalSkill] = true, [SkillType.Hit] = true, [SkillType.Area] = true, [SkillType.AreaSpell] = true, [SkillType.SpellCanRepeat] = true, [SkillType.SkillCanTrap] = true, [SkillType.SkillCanMine] = true, [SkillType.SkillCanTotem] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.6,
	baseFlags = {
	},
	baseMods = {
	skill("showAverage", true),
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"brand_detonate_faster_activation_%_per_second",
		"brand_detonate_faster_duration_%_per_second",
		"display_brand_deonate_tag_conversion",
	},
	levels = {
		[20] = { 0.80000001192093, 1.2000000476837, 25, 150, critChance = 5, manaCost = 20, damageEffectiveness = 4.3, cooldown = 1.5,
		levelRequirement = 70, statInterpolation = { 3, 3, 1, 1, }, },
	},
}



skills["SummonHarbingerOfTheArcaneUber"] = {
	name = "召唤高等秘法先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的先驱者。它会偶尔对你施放下列增益法术：秘术增强，总法术伤害、总施法速度、总魔力回复速度额外提高，以及一个有几率导致感电并穿透闪电抗性的增益效果。",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 6, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["SummonHarbingerOfBrutalityUber"] = {
	name = "召唤高等残暴先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的先驱者。当你周围有稀有或传奇敌人时，它会偶尔给你提供一个增益效果，大幅提高伤害、攻击速度和移动速度，降低你受到的伤害。并使被你击败的敌人爆炸，造成其最大生命 10% 的物理伤害。",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 11, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["SummonHarbingerOfDirectionsUber"] = {
	name = "召唤高等射术先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的先驱者。它会对你施放随机增益，附加以下任意一个或全部效果：发射 2 个额外投射物，额外连锁 2 次，投射物穿透 2 个额外目标，或者投射物分裂时额外分裂一次。",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 9, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["SummonHarbingerOfFocusUber"] = {
	name = "召唤高等不屈先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的先驱者。它会在你持续吟唱时偶尔会对你施放一个增益效果，减少你受到的伤害，使你避免所有晕眩和异常状态，并免受诅咒影响。",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 8, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["SummonHarbingerOfStormsUber"] = {
	name = "召唤高等冰雷先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的先驱者。它会偶尔对敌人施加提高效果的冰缓或感电效果，并连锁给周围其它敌人。",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	minionSkillTypes = { [SkillType.NonHitChill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 10, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}
skills["SummonHarbingerOfTimeUber"] = {
	name = "召唤高等时空先驱者",
	hidden = true,
	color = 4,
	description = "召唤一个不死的先驱者。它会偶尔对你施放光环，增加你和你周围所有队友的行动速度。",
	skillTypes = { [SkillType.Triggerable] = true, [SkillType.SkillCanMine] = true, [SkillType.Minion] = true, [SkillType.CreateMinion] = true, [SkillType.SpellCanRepeat] = true, [SkillType.Spell] = true, [SkillType.SkillCanTotem] = true, [SkillType.SkillCanTrap] = true, [SkillType.CreatesMinion] = true, [SkillType.Type90] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 1,
	cannotBeSupported = true,
	fromItem = true,
	baseFlags = {
		spell = true,
		minion = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"alternate_minion",
		"display_one_harbinger_allowed",
	},
	levels = {
		[1] = { 7, cooldown = 6, levelRequirement = 1, statInterpolation = { 1, }, },
	},
}


skills["AvianTornado"] = {
name = "鸟之龙卷",
	hidden = true,
	color = 3,
	baseEffectiveness = 2.1300001144409,
	incrementalEffectiveness = 0.02559999935329,
	description = "发出一个无法预测，带有穿刺特性的龙卷投射物，该投射物将随机移动一段时间，并反复对接触的敌人造成伤害。",
	skillTypes = { [SkillType.Spell] = true, [SkillType.Projectile] = true, [SkillType.SkillCanVolley] = true, [SkillType.Hit] = true, [SkillType.Duration] = true, [SkillType.Triggerable] = true, [SkillType.Triggered] = true, [SkillType.TriggeredGrantedSkill] = true, [SkillType.PhysicalSkill] = true, },
	statDescriptionScope = "skill_stat_descriptions",
	castTime = 0.65,
	fromItem = true,
	baseFlags = {
		spell = true,
		projectile = true,
		duration = true,
	},
	baseMods = {
	},
	qualityStats = {
	},
	stats = {
		"spell_minimum_base_physical_damage",
		"spell_maximum_base_physical_damage",
		"base_skill_effect_duration",
		"cast_on_gain_avians_flight_or_avians_might_%",
		"global_chance_to_blind_on_hit_%",
		"base_is_projectile",
		"projectiles_nova",
		"always_pierce",
		"spell_uncastable_if_triggerable",
	},
	levels = {
		[20] = { 0.80000001192093, 1.2000000476837, 2500, 100, 25, critChance = 6, levelRequirement = 70, statInterpolation = { 3, 3, 1, 1, 1, }, },
	},
}
